/* No external dependencies, network requests, telemetry or remote image processing. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id),C=window.ContourCore;
  const MAX_PIXELS=24_000_000,MAX_SIDE=8192,MAX_LAYER_PIXELS=120_000_000,HISTORY_BYTES=96*1024*1024;
  let width=960,height=720,layers=[],activeId='',selection=null,selectionCount=0,tool='brush',zoom=1,revision=0,revisionCounter=0,savedRevision=0,filename='Без названия',started=false;
  let undoStack=[],redoStack=[],space=false,gesture=null,layerCounter=0,lastPoint=null,lastSelectionSeed=null,selectionImage=null,opacityBefore=null;
  const display=$('display'),ctx=display.getContext('2d',{willReadFrequently:true}),overlay=$('overlay'),ox=overlay.getContext('2d'),viewport=$('viewport'),wrap=$('canvasWrap');
  function canvas(w=width,h=height){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
  function context(c){return c.getContext('2d',{willReadFrequently:true});}
  function active(){return layers.find(l=>l.id===activeId);}
  function layer(name,c=canvas()){return{id:'layer-'+(++layerCounter),name,canvas:c,visible:true,locked:false,opacity:1,blend:'source-over'};}
  function tell(message){$('status').textContent=message;}
  function fileNotice(message,error=false){const notice=$('fileNotice');notice.hidden=!message;notice.classList.toggle('error',error);notice.setAttribute('role',error?'alert':'status');$('fileNoticeText').textContent=message||'';}
  function validateSize(w,h){if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>MAX_SIDE||h>MAX_SIDE||w*h>MAX_PIXELS)throw Error('Изображение '+w+' × '+h+' px превышает допустимый размер. Поддерживается до 24 миллионов пикселей и до 8192 px по каждой стороне.');}
  function canAdd(count=1){if((layers.length+count)*width*height>MAX_LAYER_PIXELS||layers.length+count>40){tell('Достигнут предел слоёв для этого размера холста.');return false;}return true;}
  function editable(){const l=active();if(!l)return false;if(l.locked){tell('Слой защищён. Снимите замок, чтобы редактировать его.');return false;}if(!l.visible){tell('Слой скрыт. Включите его видимость перед редактированием.');return false;}return true;}
  function pixels(c){return context(c).getImageData(0,0,width,height);}
  function snapshot(){return{layers:layers.map(l=>({...l,canvas:undefined,data:pixels(l.canvas)})),activeId,selection:selection?.slice()||null,revision};}
  function stateBytes(s){return s.layers.length*width*height*4+(s.selection?.length||0);}
  function trimHistory(stack){let bytes=stack.reduce((n,s)=>n+stateBytes(s),0);while(stack.length>1&&(bytes>HISTORY_BYTES||stack.length>25))bytes-=stateBytes(stack.shift());}
  function changed(before){if(before){undoStack.push(before);trimHistory(undoStack);}redoStack=[];revision=++revisionCounter;started=true;$('welcome').hidden=true;updateDirty();render();renderLayers();}
  function updateDirty(){$('dirtyMark').hidden=revision===savedRevision;$('docName').textContent=filename;$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;}
  function restore(s){layers=s.layers.map(l=>{const c=canvas();context(c).putImageData(l.data,0,0);const result={...l,canvas:c};delete result.data;return result;});activeId=s.activeId;revision=s.revision;setSelection(s.selection);render();renderLayers();updateDirty();}
  function undo(){if(gesture)finishGesture();if(!undoStack.length)return;redoStack.push(snapshot());trimHistory(redoStack);restore(undoStack.pop());tell('Действие отменено.');}
  function redo(){if(!redoStack.length)return;undoStack.push(snapshot());trimHistory(undoStack);restore(redoStack.pop());tell('Действие повторено.');}
  function composite(target=ctx){target.clearRect(0,0,width,height);for(const l of layers){if(!l.visible)continue;target.globalAlpha=l.opacity;target.globalCompositeOperation=l.blend;target.drawImage(l.canvas,0,0);}target.globalAlpha=1;target.globalCompositeOperation='source-over';}
  function render(){composite();renderOverlay();}
  function resizeDisplay(){display.width=overlay.width=width;display.height=overlay.height=height;$('dimensions').textContent=width+' × '+height+' px';applyZoom();}
  function applyZoom(){wrap.style.width=width*zoom+'px';wrap.style.height=height*zoom+'px';wrap.classList.toggle('pixel-view',zoom>1);const control=$('zoom100'),percent=zoom*100;control.options[0].textContent=Math.round(percent)+'%';control.value=[...control.options].some(o=>o.value!=='custom'&&Math.abs(Number(o.value)-percent)<.001)?String(Math.round(percent)):'custom';$('zoomOut').disabled=zoom<=.02;$('zoomIn').disabled=zoom>=64;}
  function fit(){zoom=Math.max(.02,Math.min(1,(viewport.clientWidth-72)/width,(viewport.clientHeight-72)/height));applyZoom();viewport.scrollLeft=viewport.scrollTop=0;}
  function setZoom(value,clientX,clientY){if(gesture)finishGesture();const r=wrap.getBoundingClientRect(),old=zoom;const view=viewport.getBoundingClientRect(),px=(clientX??(Math.max(r.left,view.left)+Math.min(r.left+width*old,view.left+viewport.clientWidth))/2)-r.left,py=(clientY??(Math.max(r.top,view.top)+Math.min(r.top+height*old,view.top+viewport.clientHeight))/2)-r.top;zoom=Math.max(.02,Math.min(64,value));applyZoom();viewport.scrollLeft+=px*(zoom/old-1);viewport.scrollTop+=py*(zoom/old-1);}
  function renderLayers(){
    const list=$('layers');list.replaceChildren();
    for(const l of [...layers].reverse()){
      const row=document.createElement('div');row.className='layer-row'+(l.id===activeId?' active':'');row.dataset.id=l.id;
      const show=document.createElement('button');show.textContent=l.visible?'◉':'○';show.setAttribute('aria-label',(l.visible?'Скрыть':'Показать')+' слой '+l.name);show.setAttribute('aria-pressed',String(l.visible));show.onclick=e=>{e.stopPropagation();const s=snapshot();l.visible=!l.visible;changed(s);};
      const thumb=document.createElement('img');const small=canvas(34,30);context(small).drawImage(l.canvas,0,0,34,30);thumb.src=small.toDataURL();thumb.alt='';
      const name=document.createElement('span');name.className='layer-name';name.textContent=l.name;name.title=l.name+' · двойной щелчок для переименования';name.ondblclick=e=>{e.stopPropagation();const result=prompt('Название слоя',l.name);if(result?.trim()&&result.trim()!==l.name){const s=snapshot();l.name=result.trim().slice(0,120);changed(s);}};
      const lock=document.createElement('button');lock.textContent=l.locked?'▣':'◇';lock.title=l.locked?'Снять защиту':'Защитить слой';lock.setAttribute('aria-label',lock.title+' '+l.name);lock.setAttribute('aria-pressed',String(l.locked));lock.onclick=e=>{e.stopPropagation();const s=snapshot();l.locked=!l.locked;changed(s);};
      row.append(show,thumb,name,lock);row.onclick=()=>{activeId=l.id;renderLayers();};list.append(row);
    }
    const l=active();if(l){$('layerOpacity').value=Math.round(l.opacity*100);$('layerOpacityOut').value=Math.round(l.opacity*100)+'%';$('blendMode').value=l.blend;}
    const i=layers.indexOf(l);$('layerUp').disabled=i===layers.length-1;$('layerDown').disabled=i<=0;$('deleteLayer').disabled=layers.length<=1;
  }
  function setSelection(mask){selection=mask;selectionCount=C.maskCount(mask);if(!selectionCount)selection=null;lastSelectionSeed=null;selectionImage=null;
    if(selection){selectionImage=ox.createImageData(width,height);const a=selectionImage.data;for(let i=0;i<selection.length;i++){if(!selection[i])continue;const x=i%width,y=Math.floor(i/width),edge=x===0||x===width-1||y===0||y===height-1||!selection[i-1]||!selection[i+1]||!selection[i-width]||!selection[i+width];const p=i*4;if(edge){const v=(x+y)%8<4?255:24;a[p]=a[p+1]=a[p+2]=v;a[p+3]=220;}else{a[p]=124;a[p+1]=102;a[p+2]=239;a[p+3]=42;}}}
    $('selectionInfo').textContent=selectionCount?selectionCount.toLocaleString('ru-RU')+' px выделено':'Без выделения';$('copySelection').disabled=$('moveSelection').disabled=!selectionCount;$('invertSelection').disabled=$('deselect').disabled=!selectionCount;renderOverlay();
  }
  function renderOverlay(){ox.clearRect(0,0,width,height);if(selectionImage)ox.putImageData(selectionImage,0,0);if(gesture?.kind==='rect'){const a=gesture.start,b=gesture.last;ox.strokeStyle='#111';ox.lineWidth=1/zoom;ox.setLineDash([4/zoom,4/zoom]);ox.strokeRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(a.x-b.x),Math.abs(a.y-b.y));ox.setLineDash([]);}}
  function selectTool(value){tool=value;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===tool));$('brushSizeControl').hidden=tool==='pencil';$('pencilSizeControl').hidden=tool!=='pencil';viewport.style.cursor={brush:'crosshair',pencil:'crosshair',eraser:'crosshair',fill:'crosshair',colorSelect:'crosshair',rect:'crosshair',move:'move',picker:'crosshair',pan:'grab'}[tool];}
  function point(e){const r=wrap.getBoundingClientRect();return{x:(e.clientX-r.left)/zoom,y:(e.clientY-r.top)/zoom};}
  function inBounds(p){return p.x>=0&&p.y>=0&&p.x<width&&p.y<height;}
  function seedAt(p){return Math.floor(p.y)*width+Math.floor(p.x);}
  function tolerance(){return Math.max(0,Math.min(255,Number($('tolerance').value)||0));}
  function sample(){return $('sampleSource').value==='merged'?ctx.getImageData(0,0,width,height):pixels(active().canvas);}
  function selectByColor(p,e){const seed=seedAt(p),data=sample().data;const mode=e.altKey?'subtract':e.shiftKey||$('addSelection').checked?'add':'replace';const mask=C.selectColor(data,width,height,seed,tolerance(),$('contiguous').checked);setSelection(C.combineMasks(selection,mask,mode));lastSelectionSeed=mode==='replace'?{seed,data}:null;tell(selectionCount?'Выделено '+selectionCount.toLocaleString('ru-RU')+' пикселей. Ctrl J — копировать на слой.':'В этой точке нет подходящих непрозрачных пикселей.');}
  function fill(p){if(!editable())return;const region=C.floodRegion(sample().data,width,height,seedAt(p),tolerance(),selection);if(!C.maskCount(region)){tell('Точка находится за пределами выделения.');return;}const before=snapshot(),l=active(),paint=canvas(),pc=context(paint),image=pc.createImageData(width,height),rgb=parseColor();for(let i=0;i<region.length;i++){if(region[i]){const p=i*4;image.data[p]=rgb[0];image.data[p+1]=rgb[1];image.data[p+2]=rgb[2];image.data[p+3]=255;}}pc.putImageData(image,0,0);const lc=context(l.canvas);lc.globalAlpha=Number($('brushOpacity').value)/100;lc.drawImage(paint,0,0);lc.globalAlpha=1;changed(before);tell('Область залита на слое «'+l.name+'».');}
  function parseColor(){const hex=$('color').value;return[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];}
  function setColor(value){$('color').value=value;$('colorHex').value=value.toUpperCase();document.querySelectorAll('#palette button').forEach(b=>b.classList.toggle('active',b.dataset.color===value.toLowerCase()));}
  function selectionCanvas(){const c=canvas(),cc=context(c),d=cc.createImageData(width,height);for(let i=0;i<selection.length;i++)d.data[i*4+3]=selection[i]*255;cc.putImageData(d,0,0);return c;}
  function copySelection(cut){if(!selection){tell('Сначала выделите пиксели по цвету или прямоугольником.');return;}if(cut&&!editable())return;if(!canAdd())return;const source=active(),src=pixels(source.canvas);let nonempty=false;for(let i=0;i<selection.length;i++)if(selection[i]&&src.data[i*4+3]){nonempty=true;break;}if(!nonempty){tell('На текущем слое в выделении нет пикселей. Выберите слой с рисунком.');return;}const before=snapshot(),out=new ImageData(new Uint8ClampedArray(src.data.length),width,height);for(let i=0;i<selection.length;i++){if(!selection[i])continue;const p=i*4;out.data.set(src.data.subarray(p,p+4),p);if(cut)src.data.fill(0,p,p+4);}const l=layer(cut?'Перенесённое выделение':'Копия выделения');context(l.canvas).putImageData(out,0,0);if(cut)context(source.canvas).putImageData(src,0,0);layers.splice(layers.indexOf(source)+1,0,l);activeId=l.id;changed(before);tell('Выделенные пиксели '+(cut?'перенесены':'скопированы')+' на новый слой.');}
  function deletePixels(){if(!selection){tell('Для удаления пикселей сначала сделайте выделение.');return;}if(!editable())return;const before=snapshot(),l=active(),d=pixels(l.canvas);for(let i=0;i<selection.length;i++)if(selection[i])d.data.fill(0,i*4,i*4+4);context(l.canvas).putImageData(d,0,0);changed(before);tell('Выбранные пиксели удалены с текущего слоя.');}
  function extract(){if(!active().visible){tell('Выберите видимый слой с рисунком.');return;}if(!canAdd(2))return;const before=snapshot(),src=active(),d=pixels(src.canvas),converted=C.extractOutline(d.data,Number($('whitePoint').value));const contour=layer('Контур');context(contour.canvas).putImageData(new ImageData(converted,width,height),0,0);contour.locked=true;const color=layer('Цвет');src.visible=false;const i=layers.indexOf(src);layers.splice(i+1,0,color,contour);activeId=color.id;setSelection(null);changed(before);$('outlineDialog').close();tell('Контур отделён и защищён. Рисуйте на слое «Цвет». Оригинал сохранён скрытым.');}
  function beginStroke(p,e){if(!editable())return;const l=active(),pencil=tool==='pencil',brush=Math.max(1,Math.min(500,Math.round(Number($(pencil?'pencilSize':'brushSize').value)||1))),smoothing=pencil?0:Number($('brushSmoothing').value);gesture={kind:'stroke',before:snapshot(),base:canvas(),stroke:canvas(),temp:canvas(),last:p,control:p,pencil,smoother:C.strokeSmoother(p,smoothing,zoom),smooth:smoothing>0,color:$('color').value,layer:l,erase:tool==='eraser',brush,mask:selection?selectionCanvas():null,opacity:Number($('brushOpacity').value)/100,pointerId:e.pointerId};context(gesture.base).drawImage(l.canvas,0,0);const sc=context(gesture.stroke);sc.fillStyle=gesture.color;if(pencil)drawSegment(p);else{sc.beginPath();sc.arc(p.x,p.y,brush/2,0,Math.PI*2);sc.fill();}paintStroke();}
  function strokePoints(points,finish=false){const g=gesture,sc=context(g.stroke);sc.strokeStyle=g.color;sc.lineWidth=g.brush;sc.lineCap=sc.lineJoin='round';sc.beginPath();sc.moveTo(g.last.x,g.last.y);for(const p of points){if(g.smooth){const mid={x:(g.control.x+p.x)/2,y:(g.control.y+p.y)/2};sc.quadraticCurveTo(g.control.x,g.control.y,mid.x,mid.y);g.last=mid;g.control=p;}else{sc.lineTo(p.x,p.y);g.last=p;}}if(finish&&g.smooth){sc.quadraticCurveTo(g.control.x,g.control.y,g.control.x,g.control.y);g.last=g.control;}sc.stroke();}
  function drawSegment(p){const g=gesture;if(g.pencil){const sc=context(g.stroke),offset=Math.floor((g.brush-1)/2);C.pixelLine(g.last,p,(x,y)=>sc.fillRect(x-offset,y-offset,g.brush,g.brush));g.last=p;}else{const points=g.smoother.push(p);if(points.length)strokePoints([points[points.length-1]]);}}
  function scheduleStrokePaint(){const g=gesture;if(g.paintPending)return;g.paintPending=true;requestAnimationFrame(()=>{g.paintPending=false;if(gesture===g)paintStroke();});}
  function paintStroke(){const g=gesture,tc=context(g.temp);tc.globalCompositeOperation='source-over';tc.clearRect(0,0,width,height);tc.drawImage(g.stroke,0,0);if(g.mask){tc.globalCompositeOperation='destination-in';tc.drawImage(g.mask,0,0);tc.globalCompositeOperation='source-over';}const lc=context(g.layer.canvas);lc.clearRect(0,0,width,height);lc.drawImage(g.base,0,0);lc.globalAlpha=g.opacity;lc.globalCompositeOperation=g.erase?'destination-out':'source-over';lc.drawImage(g.temp,0,0);lc.globalAlpha=1;lc.globalCompositeOperation='source-over';render();}
  function finishGesture(cancel=false){if(!gesture)return;const g=gesture;if(g.kind==='stroke'&&!cancel){if(!g.pencil)strokePoints(g.smoother.finish(),true);paintStroke();}gesture=null;if(g.kind==='stroke'||g.kind==='move'){if(cancel){context(g.layer.canvas).clearRect(0,0,width,height);context(g.layer.canvas).drawImage(g.base,0,0);render();}else changed(g.before);}else if(g.kind==='rect'&&!cancel){const mask=new Uint8Array(width*height),x0=Math.max(0,Math.floor(Math.min(g.start.x,g.last.x))),x1=Math.min(width,Math.ceil(Math.max(g.start.x,g.last.x))),y0=Math.max(0,Math.floor(Math.min(g.start.y,g.last.y))),y1=Math.min(height,Math.ceil(Math.max(g.start.y,g.last.y)));for(let y=y0;y<y1;y++)mask.fill(1,y*width+x0,y*width+x1);setSelection(C.combineMasks(selection,mask,g.mode));}renderOverlay();viewport.style.cursor=tool==='pan'?'grab':viewport.style.cursor;}
  viewport.addEventListener('pointerdown',e=>{
    if(e.target.closest('#welcome'))return;if(e.button!==0&&e.button!==1)return;viewport.focus({preventScroll:true});const p=point(e);lastPoint=p;
    if(space||tool==='pan'||e.button===1){gesture={kind:'pan',startX:e.clientX,startY:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop,pointerId:e.pointerId};viewport.style.cursor='grabbing';}
    else if(!inBounds(p))return;
    else if(tool==='colorSelect')selectByColor(p,e);
    else if(tool==='picker'){const data=ctx.getImageData(Math.floor(p.x),Math.floor(p.y),1,1).data;if(data[3]){setColor('#'+[...data.slice(0,3)].map(v=>v.toString(16).padStart(2,'0')).join(''));tell('Цвет взят с видимых слоёв.');}else tell('В этой точке прозрачность.');}
    else if(tool==='fill')fill(p);
    else if(tool==='rect')gesture={kind:'rect',start:p,last:p,mode:e.altKey?'subtract':e.shiftKey||$('addSelection').checked?'add':'replace',pointerId:e.pointerId};
    else if(tool==='move'){if(!editable())return;const base=canvas();context(base).drawImage(active().canvas,0,0);gesture={kind:'move',start:p,last:p,base,layer:active(),before:snapshot(),pointerId:e.pointerId};}
    else beginStroke(p,e);
    if(gesture)viewport.setPointerCapture(e.pointerId);e.preventDefault();
  });
  viewport.addEventListener('pointermove',e=>{lastPoint=point(e);const g=gesture;if(!g||g.pointerId!==e.pointerId)return;if(g.kind==='pan'){viewport.scrollLeft=g.left+g.startX-e.clientX;viewport.scrollTop=g.top+g.startY-e.clientY;}else if(g.kind==='stroke'){const samples=e.getCoalescedEvents?.()||[];for(const sample of samples)drawSegment(point(sample));drawSegment(lastPoint);scheduleStrokePaint();}else if(g.kind==='rect'){g.last=lastPoint;renderOverlay();}else if(g.kind==='move'){g.last=lastPoint;const lc=context(g.layer.canvas);lc.clearRect(0,0,width,height);lc.drawImage(g.base,Math.round(lastPoint.x-g.start.x),Math.round(lastPoint.y-g.start.y));render();}});
  viewport.addEventListener('pointerup',e=>{if(gesture?.pointerId===e.pointerId){if(gesture.kind==='stroke')drawSegment(point(e));finishGesture();}});viewport.addEventListener('pointercancel',()=>finishGesture(true));
  viewport.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.002),e.clientX,e.clientY);}},{passive:false});
  window.addEventListener('blur',()=>{space=false;finishGesture();});
  function safeReplace(){return revision===savedRevision||confirm('В проекте есть несохранённые изменения. Открыть другой файл и оставить их без сохранения?');}
  function initialize(w,h,name,white=true){validateSize(w,h);width=w;height=h;layers=[];layerCounter=0;if(white){const bg=layer('Бумага');context(bg.canvas).fillStyle='#fff';context(bg.canvas).fillRect(0,0,w,h);bg.locked=true;layers.push(bg);}const paint=layer('Цвет');layers.push(paint);activeId=paint.id;revision=revisionCounter=savedRevision=0;filename=name;undoStack=[];redoStack=[];setSelection(null);resizeDisplay();render();renderLayers();updateDirty();requestAnimationFrame(fit);}
  async function decodeFile(file){if(file.size>80*1024*1024)throw Error('Файл слишком велик: предел 80 МБ.');const url=URL.createObjectURL(file);try{return await decodeUrl(url);}finally{URL.revokeObjectURL(url);}}
  function decodeUrl(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('Не удалось прочитать изображение. Попробуйте PNG или JPEG.'));image.src=url;});}
  async function openImageFile(file){if(!file||!safeReplace())return;try{fileNotice('Открываю «'+file.name+'»…');tell('Открываю рисунок…');const image=await decodeFile(file);validateSize(image.naturalWidth,image.naturalHeight);initialize(image.naturalWidth,image.naturalHeight,file.name,true);const original=layer('Рисунок');context(original.canvas).drawImage(image,0,0);layers.push(original);activeId=original.id;started=true;$('welcome').hidden=true;render();renderLayers();fileNotice('');tell('Рисунок открыт. W — выделить цвет; «Отделить контур» — подготовить линии к раскрашиванию.');}catch(e){const message='Не удалось открыть «'+file.name+'». '+e.message;fileNotice(message,true);tell(message);}}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function baseName(){return(filename==='Без названия'?'рисунок':filename.replace(/\.[^.]+$/,'')).replace(/[<>:"/\\|?*]/g,'_');}
  function saveProject(){if(gesture)finishGesture();try{const project={format:'contour-studio',version:1,width,height,name:filename,activeId,layers:layers.map(l=>({id:l.id,name:l.name,visible:l.visible,locked:l.locked,opacity:l.opacity,blend:l.blend,png:l.canvas.toDataURL('image/png')}))};download(new Blob([JSON.stringify(project)],{type:'application/json;charset=utf-8'}),baseName()+'.contour');savedRevision=revision;updateDirty();tell('Проект сохранён со всеми слоями.');}catch(e){tell('Не удалось сохранить проект: '+e.message);}}
  function exportPng(){if(gesture)finishGesture();const c=canvas();composite(context(c));c.toBlob(blob=>{if(!blob){tell('Не удалось экспортировать изображение.');return;}download(blob,baseName()+'.png');tell('PNG экспортирован. Для сохранения слоёв сохраните также проект.');},'image/png');}
  async function openProjectFile(file){if(!file||!safeReplace())return;try{fileNotice('Открываю проект…');if(file.size>100*1024*1024)throw Error('Проект слишком велик: предел 100 МБ.');const p=JSON.parse(await file.text());if(p.format!=='contour-studio'||p.version!==1)throw Error('Это не проект редактора «Контур» версии 1.');validateSize(p.width,p.height);if(!Array.isArray(p.layers)||!p.layers.length||p.layers.length>40||p.layers.length*p.width*p.height>MAX_LAYER_PIXELS)throw Error('В проекте слишком много слоёв.');const ids=new Set(),next=[];for(const l of p.layers){if(typeof l.id!=='string'||ids.has(l.id)||typeof l.name!=='string'||!Number.isFinite(l.opacity)||l.opacity<0||l.opacity>1||!['source-over','multiply','screen'].includes(l.blend)||typeof l.png!=='string'||!l.png.startsWith('data:image/png;base64,'))throw Error('Повреждённые данные слоя.');ids.add(l.id);const image=await decodeUrl(l.png);if(image.naturalWidth!==p.width||image.naturalHeight!==p.height)throw Error('Размеры слоя не совпадают с холстом.');const c=canvas(p.width,p.height);context(c).drawImage(image,0,0);next.push({id:l.id,name:l.name.slice(0,120),visible:!!l.visible,locked:!!l.locked,opacity:l.opacity,blend:l.blend,canvas:c});}initialize(p.width,p.height,typeof p.name==='string'?p.name.slice(0,200):file.name,false);layers=next;layerCounter=Math.max(next.length,...next.map(l=>Number(l.id.replace('layer-',''))||0));activeId=ids.has(p.activeId)?p.activeId:next[next.length-1].id;started=true;$('welcome').hidden=true;render();renderLayers();fileNotice('');tell('Проект открыт. Слои восстановлены.');}catch(e){const message='Не удалось открыть проект: '+e.message;fileNotice(message,true);tell(message);}}
  document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));
  $('openImage').onclick=$('welcomeOpen').onclick=()=>$('imageInput').click();$('imageInput').onchange=e=>{openImageFile(e.target.files[0]);e.target.value='';};
  $('dismissFileNotice').onclick=()=>fileNotice('');
  $('openProject').onclick=()=>$('projectInput').click();$('projectInput').onchange=e=>{openProjectFile(e.target.files[0]);e.target.value='';};
  $('newDoc').onclick=()=>$('newDialog').showModal();$('welcomeBlank').onclick=()=>{started=true;$('welcome').hidden=true;viewport.focus();};
  $('createDoc').onclick=()=>{try{const w=Number($('newWidth').value),h=Number($('newHeight').value);validateSize(w,h);if(!safeReplace())return;initialize(w,h,'Без названия',$('newWhite').checked);started=true;$('welcome').hidden=true;$('newDialog').close();$('newError').textContent='';tell('Новый холст создан.');}catch(e){$('newError').textContent=e.message;}};
  $('saveProject').onclick=saveProject;$('exportPng').onclick=exportPng;$('help').onclick=()=>$('helpDialog').showModal();$('undo').onclick=undo;$('redo').onclick=redo;
  $('zoomOut').onclick=()=>setZoom(zoom/1.25);$('zoomIn').onclick=()=>setZoom(zoom*1.25);$('zoom100').onchange=()=>setZoom(Number($('zoom100').value)/100);$('fit').onclick=fit;
  $('copySelection').onclick=()=>copySelection(false);$('moveSelection').onclick=()=>copySelection(true);$('deselect').onclick=()=>setSelection(null);
  $('invertSelection').onclick=()=>{if(!selection)return;const mask=new Uint8Array(selection.length);for(let i=0;i<mask.length;i++)mask[i]=1-selection[i];setSelection(mask);};
  $('extractOutline').onclick=()=>$('outlineDialog').showModal();$('doExtract').onclick=extract;$('whitePoint').oninput=()=>{$('whitePointOut').value=$('whitePoint').value;};
  $('tolerance').onchange=$('contiguous').onchange=()=>{if(!lastSelectionSeed)return;const {data,seed}=lastSelectionSeed;setSelection(C.selectColor(data,width,height,seed,tolerance(),$('contiguous').checked));lastSelectionSeed={data,seed};};
  $('addLayer').onclick=()=>{if(!canAdd())return;const s=snapshot(),l=layer('Слой '+(layerCounter+1));layers.splice(layers.indexOf(active())+1,0,l);activeId=l.id;changed(s);};
  $('duplicateLayer').onclick=()=>{if(!canAdd())return;const s=snapshot(),src=active(),l=layer(src.name+' — копия');Object.assign(l,{visible:src.visible,locked:src.locked,opacity:src.opacity,blend:src.blend});context(l.canvas).drawImage(src.canvas,0,0);layers.splice(layers.indexOf(src)+1,0,l);activeId=l.id;changed(s);};
  $('deleteLayer').onclick=()=>{if(layers.length<=1)return;if(active().locked){tell('Сначала снимите защиту слоя.');return;}const s=snapshot(),i=layers.indexOf(active());layers.splice(i,1);activeId=layers[Math.min(i,layers.length-1)].id;changed(s);};
  function reorder(delta){const i=layers.indexOf(active()),j=i+delta;if(j<0||j>=layers.length)return;const s=snapshot();[layers[i],layers[j]]=[layers[j],layers[i]];changed(s);}
  $('layerUp').onclick=()=>reorder(1);$('layerDown').onclick=()=>reorder(-1);
  $('layerOpacity').addEventListener('pointerdown',()=>{opacityBefore=snapshot();});$('layerOpacity').addEventListener('keydown',()=>{if(!opacityBefore)opacityBefore=snapshot();});
  $('layerOpacity').oninput=()=>{if(!opacityBefore)opacityBefore=snapshot();active().opacity=Number($('layerOpacity').value)/100;$('layerOpacityOut').value=$('layerOpacity').value+'%';render();};
  $('layerOpacity').onchange=()=>{if(opacityBefore){const s=opacityBefore;opacityBefore=null;changed(s);}};
  $('blendMode').onchange=()=>{const s=snapshot();active().blend=$('blendMode').value;changed(s);};
  $('brushOpacity').oninput=()=>{$('brushOpacityOut').value=$('brushOpacity').value+'%';};$('color').oninput=()=>setColor($('color').value);
  try{const value=localStorage.getItem('contour-brush-smoothing');if(value!==null&&Number.isFinite(Number(value)))$('brushSmoothing').value=Math.max(0,Math.min(100,Number(value)));}catch{}
  $('brushSmoothingOut').value=$('brushSmoothing').value+'%';
  $('brushSmoothing').oninput=()=>{$('brushSmoothingOut').value=$('brushSmoothing').value+'%';try{localStorage.setItem('contour-brush-smoothing',$('brushSmoothing').value);}catch{}};
  $('colorHex').onchange=()=>{let v=$('colorHex').value.trim();if(!v.startsWith('#'))v='#'+v;if(/^#[0-9a-f]{6}$/i.test(v))setColor(v);else{$('colorHex').value=$('color').value.toUpperCase();tell('Цвет вводится как #RRGGBB.');}};
  for(const color of ['#1e2429','#59616b','#9aa5b1','#e7e8e5','#ffffff','#ead09b','#c99358','#bd6152','#7a3c48','#b5869d','#7c68a4','#4e628a','#3f7f8a','#648b70','#9dad72','#ceb96d']){const b=document.createElement('button');b.style.background=color;b.dataset.color=color;b.title=color;b.setAttribute('aria-label','Выбрать цвет '+color);b.onclick=()=>setColor(color);$('palette').append(b);}setColor($('color').value);
  document.addEventListener('keydown',e=>{
    if(document.querySelector('dialog[open]'))return;
    if(e.target.closest('input,textarea,select,[contenteditable=true]'))return;
    const mod=e.ctrlKey||e.metaKey;let handled=true;if(gesture&&e.code!=='Space'&&e.code!=='Escape')finishGesture();
    if(mod){switch(e.code){case 'KeyZ':e.shiftKey?redo():undo();break;case 'KeyY':redo();break;case 'KeyO':$('imageInput').click();break;case 'KeyS':e.shiftKey?exportPng():saveProject();break;case 'KeyA':setSelection(new Uint8Array(width*height).fill(1));break;case 'KeyD':setSelection(null);break;case 'KeyJ':copySelection(e.shiftKey);break;default:handled=false;}}
    else if(!e.altKey){const tools={KeyB:'brush',KeyP:'pencil',KeyE:'eraser',KeyG:'fill',KeyW:'colorSelect',KeyM:'rect',KeyV:'move',KeyI:'picker',KeyH:'pan'};if(tools[e.code])selectTool(tools[e.code]);else switch(e.code){case 'Space':space=true;break;case 'Escape':if(gesture)finishGesture(true);else setSelection(null);break;case 'Delete':case 'Backspace':deletePixels();break;case 'BracketLeft':{const size=$(tool==='pencil'?'pencilSize':'brushSize');size.value=Math.max(1,Number(size.value)-(tool==='pencil'?1:5));break;}case 'BracketRight':{const size=$(tool==='pencil'?'pencilSize':'brushSize');size.value=Math.min(500,Number(size.value)+(tool==='pencil'?1:5));break;}case 'F1':$('helpDialog').showModal();break;default:handled=false;}}
    else handled=false;
    if(handled)e.preventDefault();
  });
  document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});
  window.addEventListener('beforeunload',e=>{if(revision!==savedRevision){e.preventDefault();e.returnValue='';}});
  viewport.addEventListener('dragover',e=>{e.preventDefault();});viewport.addEventListener('drop',e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f?.name.toLowerCase().endsWith('.contour'))openProjectFile(f);else openImageFile(f);});
  initialize(960,720,'Без названия');selectTool('brush');
})();
