/* No external dependencies, network requests, telemetry or remote image processing. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id),C=window.ContourCore;
  const MAX_PIXELS=24_000_000,MAX_SIDE=8192,MAX_LAYER_PIXELS=120_000_000,HISTORY_BYTES=96*1024*1024;
  const TILE_SIZE=128,thumbnails=new WeakMap();
  let width=960,height=720,layers=[],activeId='',selection=null,selectionCount=0,tool='brush',zoom=1,revision=0,revisionCounter=0,savedRevision=0,filename='Без названия',started=false;
  let undoStack=[],redoStack=[],space=false,gesture=null,layerCounter=0,lastPoint=null,lastSelectionSeed=null,opacityBefore=null;
  const display=$('display'),ctx=display.getContext('2d',{willReadFrequently:true}),overlay=$('overlay'),ox=overlay.getContext('2d'),viewport=$('viewport'),wrap=$('canvasWrap');
  const toolCursor=$('toolCursor'),selectionOutline=$('selectionOutline');let cursorPointer=null,altPicker=false,eraseHeld=false,colorSelectionMode='region',selectionTool='colorSelect',selectionCombine='replace',clipboard=null,cropBox=null,transformCache=null;
  const BLENDS=['source-over','multiply','screen','overlay','darken','lighten'];
  function temporaryPicker(){return altPicker&&['brush','pencil','eraser','fill'].includes(tool);}
  function effectiveTool(){return temporaryPicker()?'picker':eraseHeld?'eraser':tool;}
  function refreshTool(){const effective=effectiveTool();$('brushMenu').querySelectorAll('[data-brush-shape]').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.brushShape===brushShape)));document.querySelectorAll('[data-tool]').forEach(b=>{const matches=b.dataset.tool===effective||(b.dataset.tool==='brush'&&effective==='pencil')||(b.dataset.tool==='colorSelect'&&['rect','lasso'].includes(effective));b.classList.toggle('selected',matches);b.classList.toggle('temporary',(temporaryPicker()||eraseHeld)&&matches);});$('colorSelectionMenuButton').classList.toggle('selected',['colorSelect','rect','lasso'].includes(effective));$('drawingOptions').hidden=!['brush','pencil','eraser'].includes(effective);$('opacityOptions').hidden=!['brush','pencil','eraser','fill'].includes(effective);$('toleranceControl').hidden=!['colorSelect','fill'].includes(effective);$('transformOptions').hidden=effective!=='move';$('cropOptions').hidden=effective!=='crop';viewport.style.cursor={brush:'crosshair',pencil:'crosshair',eraser:'crosshair',fill:'crosshair',colorSelect:'crosshair',rect:'crosshair',lasso:'crosshair',crop:'crosshair',move:'move',picker:'crosshair',pan:'grab'}[effective];updateToolCursor();}
  function pickColor(p){const data=ctx.getImageData(Math.floor(p.x),Math.floor(p.y),1,1).data;if(data[3]){setColor('#'+[...data.slice(0,3)].map(v=>v.toString(16).padStart(2,'0')).join(''));tell('Цвет взят с видимых слоёв.');}else tell('В этой точке прозрачность.');}
  function updateToolCursor(p){
    if(!cursorPointer||cursorPointer.type==='touch'||temporaryPicker()||space||gesture?.kind==='pan'||!['brush','pencil','eraser'].includes(effectiveTool())||!$('welcome').hidden||document.querySelector('dialog[open]')){toolCursor.hidden=true;return;}
    p=p||point({clientX:cursorPointer.x,clientY:cursorPointer.y});
    const view=viewport.getBoundingClientRect();
    if(!inBounds(p)||cursorPointer.x<view.left||cursorPointer.x>=view.right||cursorPointer.y<view.top||cursorPointer.y>=view.bottom){toolCursor.hidden=true;return;}
    const g=gesture?.kind==='stroke'?gesture:null,pencil=g?g.pencil:effectiveTool()==='pencil',size=g?g.brush:Math.max(1,Math.min(500,Math.round(Number($('brushSize').value)||1))),antialias=false;
    let x,y;if(pencil){const offset=Math.floor((size-1)/2);x=Math.floor(p.x)-offset;y=Math.floor(p.y)-offset;}else{if(size===1&&!antialias)p={x:Math.floor(p.x)+.5,y:Math.floor(p.y)+.5};x=p.x-size/2;y=p.y-size/2;}
    const color=g?g.color:$('color').value,erase=g?g.erase:effectiveTool()==='eraser';toolCursor.style.setProperty('--cursor-color',erase?'#fff':color);toolCursor.style.backgroundColor=erase?'transparent':color+'33';toolCursor.classList.toggle('round',!pencil);toolCursor.style.width=toolCursor.style.height=size*zoom+'px';toolCursor.style.transform='translate('+x*zoom+'px,'+y*zoom+'px)';toolCursor.hidden=false;
  }
  function trackCursor(e,p){cursorPointer={x:e.clientX,y:e.clientY,type:e.pointerType||'mouse'};updateToolCursor(p);}
  function canvas(w=width,h=height){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
  function context(c){return c.getContext('2d',{willReadFrequently:true});}
  function active(){return layers.find(l=>l.id===activeId);}
  function nextLayerName(){let n=1;while(layers.some(l=>l.name==='Слой '+n))n++;return 'Слой '+n;}
  function layer(name=nextLayerName(),c=canvas()){return{id:'layer-'+(++layerCounter),name,canvas:c,visible:true,locked:false,opacity:1,blend:'source-over'};}
  function tell(message){$('status').textContent=message;if(/защищён|скрыт|Не удалось|предел|Сначала|сначала|нет пикселей|пуст|Буфер/.test(message))fileNotice(message,true);}
  function fileNotice(message,error=false){const notice=$('fileNotice');notice.hidden=!message;notice.classList.toggle('error',error);notice.setAttribute('role',error?'alert':'status');$('fileNoticeText').textContent=message||'';}
  function validateSize(w,h){if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>MAX_SIDE||h>MAX_SIDE||w*h>MAX_PIXELS)throw Error('Изображение '+w+' × '+h+' px превышает допустимый размер. Поддерживается до 24 миллионов пикселей и до 8192 px по каждой стороне.');}
  function canAdd(count=1){if((layers.length+count)*width*height>MAX_LAYER_PIXELS||layers.length+count>40){tell('Достигнут предел слоёв для этого размера холста.');return false;}return true;}
  function editable(){const l=active();if(!l)return false;if(l.locked){tell('Слой защищён. Снимите замок, чтобы редактировать его.');return false;}if(!l.visible){tell('Слой скрыт. Включите его видимость перед редактированием.');return false;}return true;}
  function pixels(c){return context(c).getImageData(0,0,width,height);}
  function snapshot(){return{width,height,layers:layers.map(l=>({...l,canvas:undefined,data:pixels(l.canvas)})),activeId,selection:selection?.slice()||null,revision};}
  function stateBytes(s){return(s.kind==='patch'?s.tiles.reduce((n,t)=>n+t.data.data.byteLength,0):s.layers.length*(s.width||width)*(s.height||height)*4)+(s.selection?.length||0);}
  function trimHistory(stack){let bytes=stack.reduce((n,s)=>n+stateBytes(s),0);while(stack.length>1&&(bytes>HISTORY_BYTES||stack.length>25))bytes-=stateBytes(stack.shift());}
  function changed(before,painted=false){transformCache=null;if(before){undoStack.push(before);trimHistory(undoStack);}redoStack=[];revision=++revisionCounter;started=true;$('welcome').hidden=true;updateDirty();if(!painted)render();renderLayers();queueDraft();}
  function updateDirty(){$('dirtyMark').hidden=revision===savedRevision;$('docName').textContent=filename;$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;}
  function markLayerChanged(l){transformCache=null;thumbnails.delete(l.canvas);pixelVersions.set(l.canvas,(pixelVersions.get(l.canvas)||0)+1);draftBlobs.delete(l.canvas);}
  function inverseState(s){if(s.kind!=='patch')return snapshot();const l=layers.find(l=>l.id===s.layerId);return{...s,activeId,selection,revision,tiles:s.tiles.map(t=>({...t,data:context(l.canvas).getImageData(t.x,t.y,t.data.width,t.data.height)}))};}
  function restore(s){if(s.kind==='patch'){const l=layers.find(l=>l.id===s.layerId);for(const t of s.tiles)context(l.canvas).putImageData(t.data,t.x,t.y);markLayerChanged(l);}else{width=s.width||width;height=s.height||height;resizeDisplay();layers=s.layers.map(l=>{const c=canvas();context(c).putImageData(l.data,0,0);const result={...l,canvas:c};delete result.data;return result;});}transformCache=null;cropBox=null;activeId=s.activeId;revision=s.revision;setSelection(s.selection);render();renderLayers();updateDirty();queueDraft();if(tool==='move'){prepareTransform();renderOverlay();}}
  function undo(){if(gesture)finishGesture();if(!undoStack.length)return;const s=undoStack.pop();redoStack.push(inverseState(s));trimHistory(redoStack);restore(s);tell('Действие отменено.');}
  function redo(){if(gesture)finishGesture();if(!redoStack.length)return;const s=redoStack.pop();undoStack.push(inverseState(s));trimHistory(undoStack);restore(s);tell('Действие повторено.');}
  function composite(target=ctx,b){const x=b?.x0||0,y=b?.y0||0,w=b?b.x1-x:width,h=b?b.y1-y:height;if(w<=0||h<=0)return;target.save();target.beginPath();target.rect(x,y,w,h);target.clip();target.clearRect(x,y,w,h);for(const l of layers){if(!l.visible)continue;target.globalAlpha=l.opacity;target.globalCompositeOperation=l.blend;target.drawImage(l.canvas,x,y,w,h,x,y,w,h);}target.restore();}
  function render(){composite();renderOverlay();}
  function resizeDisplay(){display.width=overlay.width=width;display.height=overlay.height=height;$('dimensions').textContent=width+' × '+height+' px';applyZoom();}
  function applyZoom(){wrap.style.width=width*zoom+'px';wrap.style.height=height*zoom+'px';wrap.classList.toggle('pixel-view',zoom>1);const control=$('zoom100'),percent=zoom*100;control.options[0].textContent=Math.round(percent)+'%';control.value=[...control.options].some(o=>o.value!=='custom'&&Math.abs(Number(o.value)-percent)<.001)?String(Math.round(percent)):'custom';$('zoomOut').disabled=zoom<=.02;$('zoomIn').disabled=zoom>=64;updateToolCursor();}
  function fit(){zoom=Math.max(.02,Math.min(1,(viewport.clientWidth-72)/width,(viewport.clientHeight-72)/height));applyZoom();viewport.scrollLeft=viewport.scrollTop=0;updateToolCursor();}
  function setZoom(value,clientX,clientY){if(gesture)finishGesture();const r=wrap.getBoundingClientRect(),old=zoom;const view=viewport.getBoundingClientRect(),px=(clientX??(Math.max(r.left,view.left)+Math.min(r.left+width*old,view.left+viewport.clientWidth))/2)-r.left,py=(clientY??(Math.max(r.top,view.top)+Math.min(r.top+height*old,view.top+viewport.clientHeight))/2)-r.top;zoom=Math.max(.02,Math.min(64,value));applyZoom();viewport.scrollLeft+=px*(zoom/old-1);viewport.scrollTop+=py*(zoom/old-1);updateToolCursor();}
  function renderLayers(){
    const list=$('layers');list.replaceChildren();
    for(const l of [...layers].reverse()){
      const row=document.createElement('div');row.className='layer-row'+(l.id===activeId?' active':'');row.dataset.id=l.id;
      const show=document.createElement('button');show.textContent=l.visible?'◉':'○';show.setAttribute('aria-label',(l.visible?'Скрыть':'Показать')+' слой '+l.name);show.setAttribute('aria-pressed',String(l.visible));show.onclick=e=>{e.stopPropagation();const s=snapshot();l.visible=!l.visible;changed(s);};
      const thumb=document.createElement('img');let url=thumbnails.get(l.canvas);if(!url){const small=canvas(34,30);context(small).drawImage(l.canvas,0,0,34,30);url=small.toDataURL();thumbnails.set(l.canvas,url);}thumb.src=url;thumb.alt='';
      const name=document.createElement('span');name.className='layer-name';name.textContent=l.name;name.title=l.name+' · двойной щелчок для переименования';name.ondblclick=e=>{e.stopPropagation();const result=prompt('Название слоя',l.name);if(result?.trim()&&result.trim()!==l.name){const s=snapshot();l.name=result.trim().slice(0,120);changed(s);}};
      const lock=document.createElement('button');lock.textContent=l.locked?'▣':'◇';lock.title=l.locked?'Снять защиту':'Защитить слой';lock.setAttribute('aria-label',lock.title+' '+l.name);lock.setAttribute('aria-pressed',String(l.locked));lock.onclick=e=>{e.stopPropagation();const s=snapshot();l.locked=!l.locked;changed(s);};
      row.append(show,thumb,name,lock);row.onclick=()=>{activeId=l.id;transformCache=null;renderLayers();if(tool==='move')prepareTransform();renderOverlay();};list.append(row);
    }
    const l=active();if(l){$('layerOpacity').value=Math.round(l.opacity*100);$('layerOpacityOut').value=Math.round(l.opacity*100)+'%';$('blendMode').value=l.blend;blendHint();}
    const i=layers.indexOf(l);$('layerUp').disabled=i===layers.length-1;$('layerDown').disabled=i<=0;$('deleteLayer').disabled=layers.length<=1;if(tool==='move'&&!gesture){prepareTransform();renderOverlay();}
  }
  function setSelection(mask){selection=mask;selectionCount=C.maskCount(mask);if(!selectionCount)selection=null;lastSelectionSeed=null;transformCache=null;const path=C.selectionOutline(selection,width,height);selectionOutline.setAttribute('viewBox','0 0 '+width+' '+height);selectionOutline.querySelectorAll('path').forEach(p=>p.setAttribute('d',path));$('invertSelection').disabled=$('deselect').disabled=!selectionCount;renderOverlay();}
  function renderOverlay(){ox.clearRect(0,0,width,height);selectionOutline.toggleAttribute('hidden',!selection);if(gesture?.kind==='rect'){const a=gesture.start,b=gesture.last;outlineBox({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)});}
    if(gesture?.kind==='lasso'){const pts=gesture.points;ox.strokeStyle='#fff';ox.lineWidth=1/zoom;ox.setLineDash([4/zoom,4/zoom]);ox.beginPath();ox.moveTo(pts[0].x,pts[0].y);for(const p of pts.slice(1))ox.lineTo(p.x,p.y);ox.lineTo(pts[0].x,pts[0].y);ox.stroke();ox.setLineDash([]);}
    if(tool==='crop'&&cropBox){const b=cropBox;ox.fillStyle='#0008';ox.fillRect(0,0,width,b.y);ox.fillRect(0,b.y+b.h,width,height-b.y-b.h);ox.fillRect(0,b.y,b.x,b.h);ox.fillRect(b.x+b.w,b.y,width-b.x-b.w,b.h);outlineBox(b);ox.strokeStyle='#ffffff70';ox.lineWidth=1/zoom;ox.beginPath();for(let i=1;i<3;i++){ox.moveTo(b.x+b.w*i/3,b.y);ox.lineTo(b.x+b.w*i/3,b.y+b.h);ox.moveTo(b.x,b.y+b.h*i/3);ox.lineTo(b.x+b.w,b.y+b.h*i/3);}ox.stroke();}
    if(tool==='move'&&transformCache){const b=gesture?.kind==='transform'?gesture.box:transformCache.box;outlineBox(b,true);}
  }
  function outlineBox(b,handles=false){ox.save();ox.strokeStyle='#fff';ox.lineWidth=1/zoom;ox.strokeRect(b.x,b.y,b.w,b.h);ox.strokeStyle='#111';ox.setLineDash([4/zoom,4/zoom]);ox.strokeRect(b.x,b.y,b.w,b.h);ox.setLineDash([]);if(handles){const r=4/zoom;for(const [x,y] of [[b.x,b.y],[b.x+b.w,b.y],[b.x,b.y+b.h],[b.x+b.w,b.y+b.h]]){ox.fillStyle='#fff';ox.fillRect(x-r,y-r,2*r,2*r);ox.strokeRect(x-r,y-r,2*r,2*r);}}ox.restore();}
  function selectTool(value){finishGesture();closeColorSelectionMenu();closeBrushMenu();if(value==='colorSelect')value=selectionTool;if(value==='brush'&&brushShape==='square')value='pencil';if(value==='pencil')brushShape='square';tool=value;if(['colorSelect','rect','lasso'].includes(value)){selectionTool=value;$('colorSelectionMenu').querySelectorAll('[data-selection-mode]').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.selectionMode===(value==='colorSelect'?colorSelectionMode:value))));}if(tool!=='crop'){cropBox=null;updateCropFields();}if(tool==='move')prepareTransform();refreshTool();renderOverlay();}

  function point(e){const r=wrap.getBoundingClientRect();return{x:(e.clientX-r.left)/zoom,y:(e.clientY-r.top)/zoom};}
  function inBounds(p){return p.x>=0&&p.y>=0&&p.x<width&&p.y<height;}
  function seedAt(p){return Math.floor(p.y)*width+Math.floor(p.x);}
  function tolerance(){return Math.max(0,Math.min(255,Number($('tolerance').value)||0));}
  function sample(){return ctx.getImageData(0,0,width,height);}
  function colorSelectionMask(data,seed){return colorSelectionMode==='region'?C.floodRegion(data,width,height,seed,tolerance(),null):C.selectColor(data,width,height,seed,tolerance(),false);}
  function refreshColorSelection(){if(!lastSelectionSeed)return;const {data,seed}=lastSelectionSeed;setSelection(colorSelectionMask(data,seed));lastSelectionSeed={data,seed};}
  function setColorSelectionMode(mode,reselect=true){
    if(mode==='rect'||mode==='lasso'){selectionTool=mode;}else{colorSelectionMode=mode==='global'?'global':'region';selectionTool='colorSelect';if(reselect)refreshColorSelection();}
    $('colorSelectionMenu').querySelectorAll('[data-selection-mode]').forEach(b=>b.onclick=()=>{setColorSelectionMode(b.dataset.selectionMode);selectTool(selectionTool);viewport.focus({preventScroll:true});});
  }
  function closeColorSelectionMenu(returnFocus=false){$('colorSelectionMenu').hidden=true;$('colorSelectionMenuButton').setAttribute('aria-expanded','false');if(returnFocus)$('colorSelectionMenuButton').focus({preventScroll:true});}
  function openColorSelectionMenu(){
    const menu=$('colorSelectionMenu'),button=$('colorSelectionMenuButton');menu.hidden=false;button.setAttribute('aria-expanded','true');
    const r=button.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.right+8,window.innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(r.top,window.innerHeight-menu.offsetHeight-8))+'px';
    menu.querySelector('[aria-checked="true"]').focus({preventScroll:true});
  }
  function selectByColor(p,e){const seed=seedAt(p),data=sample().data;const mode=combineMode(e);const mask=colorSelectionMask(data,seed);setSelection(C.combineMasks(selection,mask,mode));lastSelectionSeed=mode==='replace'?{seed,data}:null;tell(selectionCount?'Выделено '+selectionCount.toLocaleString('ru-RU')+' пикселей. Ctrl J — копировать на слой.':'В этой точке нет подходящих непрозрачных пикселей.');}
  function fill(p){if(!editable())return;const region=C.floodRegion(sample().data,width,height,seedAt(p),tolerance(),selection);if(!C.maskCount(region)){tell('Точка находится за пределами выделения.');return;}const before=snapshot(),l=active(),paint=canvas(),pc=context(paint),image=pc.createImageData(width,height),rgb=parseColor();for(let i=0;i<region.length;i++){if(region[i]){const p=i*4;image.data[p]=rgb[0];image.data[p+1]=rgb[1];image.data[p+2]=rgb[2];image.data[p+3]=255;}}pc.putImageData(image,0,0);const lc=context(l.canvas);lc.globalAlpha=Number($('brushOpacity').value)/100;lc.drawImage(paint,0,0);lc.globalAlpha=1;markLayerChanged(l);changed(before);tell('Область залита на слое «'+l.name+'».');}
  function parseColor(){const hex=$('color').value;return[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)];}
  function setColor(value){$('color').value=value;$('colorHex').value=value.toUpperCase();document.querySelectorAll('#palette button').forEach(b=>b.classList.toggle('active',b.dataset.color===value.toLowerCase()));updateToolCursor();}
  function selectionCanvas(){const c=canvas(),cc=context(c),d=cc.createImageData(width,height);for(let i=0;i<selection.length;i++)d.data[i*4+3]=selection[i]*255;cc.putImageData(d,0,0);return c;}
  function copyPixels(cut=false){if(cut&&!editable())return;const src=pixels(active().canvas),out=new Uint8ClampedArray(src.data.length);let x0=width,y0=height,x1=0,y1=0;for(let i=0;i<width*height;i++){if((!selection||selection[i])&&src.data[i*4+3]){out.set(src.data.subarray(i*4,i*4+4),i*4);const x=i%width,y=Math.floor(i/width);x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x+1);y1=Math.max(y1,y+1);}}if(x1<=x0){tell('На текущем слое в выделении нет пикселей.');return false;}const c=canvas(x1-x0,y1-y0),full=canvas();context(full).putImageData(new ImageData(out,width,height),0,0);context(c).drawImage(full,x0,y0,c.width,c.height,0,0,c.width,c.height);clipboard={canvas:c,x:x0,y:y0,docWidth:width,docHeight:height};if(cut){const before=snapshot();for(let i=0;i<width*height;i++)if(!selection||selection[i])src.data.fill(0,i*4,i*4+4);context(active().canvas).putImageData(src,0,0);markLayerChanged(active());changed(before);}return true;}
  function pastePixels(){if(!clipboard){tell('Буфер пуст. Сначала скопируйте пиксели: Ctrl C.');return;}if(!canAdd())return;const before=snapshot(),l=layer(),c=clipboard.canvas,x=clipboard.docWidth===width?clipboard.x:Math.floor((width-c.width)/2),y=clipboard.docHeight===height?clipboard.y:Math.floor((height-c.height)/2);context(l.canvas).drawImage(c,x,y);layers.splice(layers.indexOf(active())+1,0,l);activeId=l.id;const data=pixels(l.canvas).data;setSelection(Uint8Array.from({length:width*height},(_,i)=>Number(data[i*4+3]>0)));changed(before);}
  function copySelection(cut){if(copyPixels(cut))pastePixels();}

  function deletePixels(){if(!selection){tell('Для удаления пикселей сначала сделайте выделение.');return;}if(!editable())return;const l=active(),d=pixels(l.canvas);let nonempty=false;for(let i=0;i<selection.length;i++)if(selection[i]&&d.data[i*4+3]){nonempty=true;break;}if(!nonempty){tell('На текущем слое в выделении уже нет пикселей.');return;}const before=snapshot();for(let i=0;i<selection.length;i++)if(selection[i])d.data.fill(0,i*4,i*4+4);context(l.canvas).putImageData(d,0,0);markLayerChanged(l);changed(before);tell('Выбранные пиксели удалены с текущего слоя.');}
  function extract(){if(!active().visible){tell('Выберите видимый слой с рисунком.');return;}if(!canAdd())return;const before=snapshot(),src=active(),d=pixels(src.canvas),converted=C.extractOutline(d.data,Number($('whitePoint').value));const contour=layer('Контур');context(contour.canvas).putImageData(new ImageData(converted,width,height),0,0);src.visible=false;layers.filter(l=>l.name==='Бумага'&&l.locked).forEach(l=>l.visible=false);layers.splice(layers.indexOf(src)+1,0,contour);activeId=contour.id;setSelection(null);changed(before);$('outlineDialog').close();}
  function beginStroke(p,e){if(!editable())return;const l=active(),pencil=effectiveTool()==='pencil',brush=Math.max(1,Math.min(500,Math.round(Number($('brushSize').value)||1))),smoothing=pencil?0:50,antialias=false;if(!pencil&&!antialias&&brush===1)p={x:Math.floor(p.x)+.5,y:Math.floor(p.y)+.5};gesture={kind:'stroke',before:{kind:'patch',layerId:l.id,activeId,selection,revision,tiles:[]},captured:new Set(),stroke:canvas(),temp:canvas(),last:p,control:p,pencil,antialias,bounds:null,smoother:C.strokeSmoother(p,smoothing,zoom),smooth:smoothing>0,color:$('color').value,layer:l,erase:effectiveTool()==='eraser',brush,mask:selection?selectionCanvas():null,opacity:Number($('brushOpacity').value)/100,pointerId:e.pointerId};extendStrokeBounds(p);const sc=context(gesture.stroke);sc.fillStyle=gesture.color;if(pencil)drawSegment(p);else{sc.beginPath();sc.arc(p.x,p.y,brush/2,0,Math.PI*2);sc.fill();}paintStroke();}
  function strokePoints(points,finish=false){const g=gesture,sc=context(g.stroke);sc.strokeStyle=g.color;sc.lineWidth=g.brush;sc.lineCap=sc.lineJoin='round';sc.beginPath();sc.moveTo(g.last.x,g.last.y);for(const p of points){extendStrokeBounds(g.last);extendStrokeBounds(g.control);extendStrokeBounds(p);if(g.smooth){const mid={x:(g.control.x+p.x)/2,y:(g.control.y+p.y)/2};sc.quadraticCurveTo(g.control.x,g.control.y,mid.x,mid.y);g.last=mid;g.control=p;}else{sc.lineTo(p.x,p.y);g.last=p;}}if(finish&&g.smooth){extendStrokeBounds(g.last);extendStrokeBounds(g.control);sc.quadraticCurveTo(g.control.x,g.control.y,g.control.x,g.control.y);g.last=g.control;}sc.stroke();}
  function extendStrokeBounds(p){const g=gesture,r=g.brush/2+2,b=g.bounds||(g.bounds={x0:width,y0:height,x1:0,y1:0});b.x0=Math.max(0,Math.min(b.x0,Math.floor(p.x-r)));b.y0=Math.max(0,Math.min(b.y0,Math.floor(p.y-r)));b.x1=Math.min(width,Math.max(b.x1,Math.ceil(p.x+r)));b.y1=Math.min(height,Math.max(b.y1,Math.ceil(p.y+r)));}
  // Preserve each original tile once, before the first preview can change it.
  function captureStrokeTiles(g,b){const lc=context(g.layer.canvas);for(let y=Math.floor(b.y0/TILE_SIZE)*TILE_SIZE;y<b.y1;y+=TILE_SIZE){for(let x=Math.floor(b.x0/TILE_SIZE)*TILE_SIZE;x<b.x1;x+=TILE_SIZE){const key=x+','+y;if(g.captured.has(key))continue;g.captured.add(key);g.before.tiles.push({x,y,data:lc.getImageData(x,y,Math.min(TILE_SIZE,width-x),Math.min(TILE_SIZE,height-y))});}}}
  function restoreStrokeRegion(g,b){const lc=context(g.layer.canvas);for(const t of g.before.tiles){const x=Math.max(t.x,b.x0),y=Math.max(t.y,b.y0),w=Math.min(t.x+t.data.width,b.x1)-x,h=Math.min(t.y+t.data.height,b.y1)-y;if(w>0&&h>0)lc.putImageData(t.data,t.x,t.y,x-t.x,y-t.y,w,h);}}
  function drawSegment(p){const g=gesture;if(!g.pencil&&!g.antialias&&g.brush===1)p={x:Math.floor(p.x)+.5,y:Math.floor(p.y)+.5};extendStrokeBounds(p);if(g.pencil){extendStrokeBounds(g.last);const sc=context(g.stroke),offset=Math.floor((g.brush-1)/2);C.pixelLine(g.last,p,(x,y)=>sc.fillRect(x-offset,y-offset,g.brush,g.brush));g.last=p;}else{const points=g.smoother.push(p);if(points.length)strokePoints([points[points.length-1]]);}}
  function scheduleStrokePaint(){const g=gesture;if(g.paintPending)return;g.paintPending=true;requestAnimationFrame(()=>{g.paintPending=false;if(gesture===g)paintStroke();});}
  function paintStroke(){const g=gesture,b=g.bounds;if(!b)return;g.bounds=null;const x=b.x0,y=b.y0,bw=b.x1-x,bh=b.y1-y;if(bw<=0||bh<=0)return;captureStrokeTiles(g,b);const tc=context(g.temp);tc.save();tc.beginPath();tc.rect(x,y,bw,bh);tc.clip();tc.globalCompositeOperation='source-over';tc.clearRect(x,y,bw,bh);tc.drawImage(g.stroke,x,y,bw,bh,x,y,bw,bh);if(!g.antialias&&!g.pencil){const image=tc.getImageData(x,y,bw,bh),data=image.data,rgb=[1,3,5].map(i=>parseInt(g.color.slice(i,i+2),16));for(let i=0;i<data.length;i+=4){data[i+3]=data[i+3]>=128?255:0;if(data[i+3]){data[i]=rgb[0];data[i+1]=rgb[1];data[i+2]=rgb[2];}}tc.putImageData(image,x,y);}if(g.mask){tc.globalCompositeOperation='destination-in';tc.drawImage(g.mask,x,y,bw,bh,x,y,bw,bh);}tc.restore();restoreStrokeRegion(g,b);const lc=context(g.layer.canvas);lc.save();lc.beginPath();lc.rect(x,y,bw,bh);lc.clip();lc.globalAlpha=g.opacity;lc.globalCompositeOperation=g.erase?'destination-out':'source-over';lc.drawImage(g.temp,x,y,bw,bh,x,y,bw,bh);lc.restore();composite(ctx,b);}
  function finishGesture(cancel=false){if(!gesture)return;const g=gesture;if(g.kind==='stroke'&&!cancel){if(!g.pencil)strokePoints(g.smoother.finish(),true);paintStroke();}gesture=null;if(g.kind==='stroke'){if(cancel){for(const t of g.before.tiles)context(g.layer.canvas).putImageData(t.data,t.x,t.y);render();}else{markLayerChanged(g.layer);changed(g.before,true);}}else if(g.kind==='transform'){if(cancel){context(g.layer.canvas).clearRect(0,0,width,height);context(g.layer.canvas).drawImage(g.base,0,0);render();}else commitTransform(g);}else if(g.kind==='rect'&&!cancel){const mask=new Uint8Array(width*height),x0=Math.max(0,Math.floor(Math.min(g.start.x,g.last.x))),x1=Math.min(width,Math.ceil(Math.max(g.start.x,g.last.x))),y0=Math.max(0,Math.floor(Math.min(g.start.y,g.last.y))),y1=Math.min(height,Math.ceil(Math.max(g.start.y,g.last.y)));for(let y=y0;y<y1;y++)if(x1>x0)mask.fill(1,y*width+x0,y*width+x1);setSelection(C.combineMasks(selection,mask,g.mode));}else if(g.kind==='lasso'&&!cancel){g.points.push(...g.smoother.finish());setSelection(C.combineMasks(selection,C.polygonMask(g.points,width,height),g.mode));}else if(g.kind==='crop'&&cancel){cropBox=g.previous;updateCropFields();}renderOverlay();refreshTool();}
  viewport.addEventListener('pointerdown',e=>{
    if(e.target.closest('#welcome'))return;if(e.button!==0&&e.button!==1)return;viewport.focus({preventScroll:true});const p=point(e);lastPoint=p;trackCursor(e,p);const effective=effectiveTool();
    if(space||effective==='pan'||e.button===1){gesture={kind:'pan',startX:e.clientX,startY:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop,pointerId:e.pointerId};viewport.style.cursor='grabbing';}
    else if(!inBounds(p))return;
    else if(effective==='colorSelect')selectByColor(p,e);
    else if(effective==='picker'||(e.altKey&&!e.ctrlKey&&!e.metaKey&&['brush','pencil','eraser','fill'].includes(effective)))pickColor(p);
    else if(effective==='fill')fill(p);
    else if(effective==='rect')gesture={kind:'rect',start:p,last:p,mode:combineMode(e),pointerId:e.pointerId};
    else if(effective==='lasso')gesture={kind:'lasso',points:[p],smoother:C.strokeSmoother(p,50,zoom),mode:combineMode(e),pointerId:e.pointerId};
    else if(effective==='crop'){gesture={kind:'crop',start:p,last:p,previous:cropBox,pointerId:e.pointerId};cropBox={x:Math.floor(p.x),y:Math.floor(p.y),w:1,h:1};updateCropFields();renderOverlay();}
    else if(effective==='move')beginTransform(p,e);
    else beginStroke(p,e);
    if(gesture)viewport.setPointerCapture(e.pointerId);updateToolCursor(p);e.preventDefault();
  });

  viewport.addEventListener('pointerenter',e=>trackCursor(e));viewport.addEventListener('pointerleave',()=>{cursorPointer=null;updateToolCursor();});viewport.addEventListener('scroll',()=>updateToolCursor(),{passive:true});window.addEventListener('resize',()=>updateToolCursor());
  viewport.addEventListener('pointermove',e=>{lastPoint=point(e);trackCursor(e,lastPoint);const g=gesture;if(!g||g.pointerId!==e.pointerId)return;if(g.kind==='pan'){viewport.scrollLeft=g.left+g.startX-e.clientX;viewport.scrollTop=g.top+g.startY-e.clientY;}else if(g.kind==='stroke'){const samples=e.getCoalescedEvents?.()||[];for(const sample of samples)drawSegment(point(sample));drawSegment(lastPoint);scheduleStrokePaint();}else if(g.kind==='rect'){g.last=lastPoint;renderOverlay();}else if(g.kind==='lasso'){const pts=g.smoother.push(lastPoint);if(pts.length)g.points.push(pts.at(-1));renderOverlay();}else if(g.kind==='crop'){cropBox=cropFromPoints(g.start,lastPoint);updateCropFields();renderOverlay();}else if(g.kind==='transform')dragTransform(g,lastPoint);});
  viewport.addEventListener('pointerup',e=>{if(gesture?.pointerId===e.pointerId){if(gesture.kind==='stroke')drawSegment(point(e));finishGesture();}});viewport.addEventListener('pointercancel',()=>finishGesture(true));
  viewport.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.002),e.clientX,e.clientY);}},{passive:false});
  window.addEventListener('blur',()=>{space=false;altPicker=false;eraseHeld=false;refreshTool();cursorPointer=null;finishGesture();updateToolCursor();});
  const draftStore=window.ContourDraftStore,draftBlobs=new WeakMap(),pixelVersions=new WeakMap();
  let draftGeneration=0,draftSavedGeneration=-1,draftTimer=null,draftJob=null,draftQueued=false,draftReady=false,pendingDraft=null;
  function draftStatus(message,error=false){$('draftStatus').textContent=message;$('draftStatus').classList.toggle('error',error);}
  function queueDraft(){draftGeneration++;scheduleDraft();}
  function scheduleDraft(){if(!draftReady||!draftStore||!started)return;clearTimeout(draftTimer);draftStatus('Черновик: ожидает записи');draftTimer=setTimeout(()=>saveDraft(),1200);}
  function encodedLayer(l){const version=pixelVersions.get(l.canvas)||0,cached=draftBlobs.get(l.canvas);if(cached?.version===version)return Promise.resolve(cached.blob);return new Promise((resolve,reject)=>l.canvas.toBlob(blob=>{if(!blob){reject(Error('Cannot encode layer'));return;}if((pixelVersions.get(l.canvas)||0)===version&&gesture?.layer?.canvas!==l.canvas)draftBlobs.set(l.canvas,{version,blob});resolve(blob);},'image/png'));}
  async function saveDraft(){
    if(!draftReady||!draftStore||!started||draftSavedGeneration===draftGeneration)return;
    if(gesture||opacityBefore){scheduleDraft();return;}
    if(draftJob){draftQueued=true;return draftJob;}
    clearTimeout(draftTimer);const generation=draftGeneration,w=width,h=height,name=filename,id=activeId,source=layers.map(l=>({...l}));
    const settings={tool,colorSelectionMode,color:$('color').value,brushSize:$('brushSize').value,opacity:$('brushOpacity').value};
    draftStatus('Черновик: сохраняю…');
    draftJob=(async()=>{
      try{
        const encoded=await Promise.all(source.map(async l=>({id:l.id,name:l.name,visible:l.visible,locked:l.locked,opacity:l.opacity,blend:l.blend,png:await encodedLayer(l)})));
        if(generation!==draftGeneration||gesture){draftQueued=true;return;}
        const savedAt=Date.now();await draftStore.write({format:'contour-draft',version:1,width:w,height:h,name,activeId:id,layers:encoded,settings,savedAt});
        if(generation===draftGeneration){draftSavedGeneration=generation;draftStatus('Черновик сохранён · '+new Date(savedAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'}));}else draftQueued=true;
      }catch(e){draftStatus('Черновик не сохранён — сохраните проект',true);}
      finally{draftJob=null;if(draftQueued){draftQueued=false;scheduleDraft();}}
    })();return draftJob;
  }
  async function findDraft(){
    if(!draftStore){draftStatus('Черновик недоступен',true);return;}
    try{const draft=await draftStore.read();draftReady=true;if(draft&&draft.format==='contour-draft'&&draft.version===1&&!started){pendingDraft=draft;$('draftDescription').textContent=(draft.name||'Без названия')+' · '+new Date(draft.savedAt).toLocaleString('ru-RU');$('draftDialog').showModal();draftStatus('Черновик найден');}else{draftStatus('Черновик: готов');if(started)scheduleDraft();}}catch(e){draftReady=true;draftStatus('Черновик недоступен — сохраните проект',true);}
  }
  async function restoreDraft(){
    const p=pendingDraft;if(!p)return;const button=$('restoreDraft');button.disabled=true;$('skipDraft').disabled=true;$('draftError').textContent='';
    try{
      validateSize(p.width,p.height);if(!Array.isArray(p.layers)||!p.layers.length||p.layers.length>40||p.layers.length*p.width*p.height>MAX_LAYER_PIXELS)throw Error('Некорректное число слоёв.');
      const ids=new Set(),next=[];
      for(const l of p.layers){
        if(typeof l.id!=='string'||ids.has(l.id)||typeof l.name!=='string'||!Number.isFinite(l.opacity)||l.opacity<0||l.opacity>1||!BLENDS.includes(l.blend)||!(l.png instanceof Blob)||l.png.type!=='image/png')throw Error('Повреждённые данные слоя.');
        ids.add(l.id);const url=URL.createObjectURL(l.png);let image;try{image=await decodeUrl(url);}finally{URL.revokeObjectURL(url);}if(image.naturalWidth!==p.width||image.naturalHeight!==p.height)throw Error('Размеры слоя не совпадают с холстом.');
        const c=canvas(p.width,p.height);context(c).drawImage(image,0,0);next.push({id:l.id,name:l.name.slice(0,120),visible:!!l.visible,locked:!!l.locked,opacity:l.opacity,blend:l.blend,canvas:c});
      }
      initialize(p.width,p.height,typeof p.name==='string'?p.name.slice(0,200):'Без названия',false);layers=next;layerCounter=Math.max(next.length,...next.map(l=>Number(l.id.replace('layer-',''))||0));activeId=ids.has(p.activeId)?p.activeId:next.at(-1).id;revision=revisionCounter=1;savedRevision=0;started=true;$('welcome').hidden=true;
      const settings=p.settings||{};setColorSelectionMode(settings.colorSelectionMode,false);for(const [key,id,max] of [['brushSize','brushSize',500],['opacity','brushOpacity',100]]){if(Number.isFinite(Number(settings[key])))$(id).value=Math.max(1,Math.min(max,Number(settings[key])));}
      $('brushOpacityOut').value=$('brushOpacity').value+'%';if(/^#[0-9a-f]{6}$/i.test(settings.color))setColor(settings.color);if(['brush','pencil','eraser','fill','colorSelect','rect','lasso','crop','move','picker','pan'].includes(settings.tool))selectTool(settings.tool);

      $('draftDialog').close();pendingDraft=null;draftGeneration++;draftSavedGeneration=draftGeneration;render();renderLayers();updateDirty();draftStatus('Черновик восстановлен');tell('Черновик восстановлен со всеми слоями.');
    }catch(e){$('draftError').textContent='Не удалось восстановить черновик. '+e.message;}
    finally{button.disabled=false;$('skipDraft').disabled=false;}
  }
  $('restoreDraft').onclick=restoreDraft;$('skipDraft').onclick=()=>{pendingDraft=null;$('draftDialog').close();draftStatus('Черновик: готов');};
  $('draftDialog').addEventListener('cancel',()=>{pendingDraft=null;draftStatus('Черновик: готов');});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){finishGesture();saveDraft();}});
  function safeReplace(){return revision===savedRevision||confirm('В проекте есть несохранённые изменения. Открыть другой файл и оставить их без сохранения?');}
  function initialize(w,h,name,white=true){validateSize(w,h);transformCache=null;cropBox=null;width=w;height=h;layers=[];layerCounter=0;if(white){const bg=layer('Бумага');context(bg.canvas).fillStyle='#fff';context(bg.canvas).fillRect(0,0,w,h);bg.locked=true;layers.push(bg);}const paint=layer('Слой 1');layers.push(paint);activeId=paint.id;revision=revisionCounter=savedRevision=0;filename=name;undoStack=[];redoStack=[];updateCropFields();setSelection(null);resizeDisplay();render();renderLayers();updateDirty();requestAnimationFrame(fit);}
  async function decodeFile(file){if(file.size>80*1024*1024)throw Error('Файл слишком велик: предел 80 МБ.');const url=URL.createObjectURL(file);try{return await decodeUrl(url);}finally{URL.revokeObjectURL(url);}}
  function decodeUrl(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('Не удалось прочитать изображение. Попробуйте PNG или JPEG.'));image.src=url;});}
  async function openImageFile(file){if(!file||!safeReplace())return;try{fileNotice('Открываю «'+file.name+'»…');tell('Открываю рисунок…');let image;if(/\.tiff?$/i.test(file.name)){if(file.size>100*1024*1024)throw Error('TIFF слишком велик.');const decoded=window.ContourFormats.decodeTiff(await file.arrayBuffer(),validateSize);image=canvas(decoded.width,decoded.height);context(image).putImageData(new ImageData(decoded.data,decoded.width,decoded.height),0,0);image.naturalWidth=decoded.width;image.naturalHeight=decoded.height;}else image=await decodeFile(file);validateSize(image.naturalWidth,image.naturalHeight);initialize(image.naturalWidth,image.naturalHeight,file.name,true);const original=active();context(original.canvas).drawImage(image,0,0);markLayerChanged(original);started=true;$('welcome').hidden=true;render();renderLayers();fileNotice('');queueDraft();tell('Рисунок открыт. W — выделить цвет; «Удалить фон» — подготовить линии к раскрашиванию.');}catch(e){const message='Не удалось открыть «'+file.name+'». '+e.message;fileNotice(message,true);tell(message);}}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function baseName(){return(filename==='Без названия'?'рисунок':filename.replace(/\.[^.]+$/,'')).replace(/[<>:"/\\|?*]/g,'_');}
  function saveProject(){if(gesture)finishGesture();try{const project={format:'contour-studio',version:1,width,height,name:filename,activeId,layers:layers.map(l=>({id:l.id,name:l.name,visible:l.visible,locked:l.locked,opacity:l.opacity,blend:l.blend,png:l.canvas.toDataURL('image/png')}))};download(new Blob([JSON.stringify(project)],{type:'application/json;charset=utf-8'}),baseName()+'.contour');savedRevision=revision;updateDirty();tell('Проект сохранён со всеми слоями.');}catch(e){throw Error('Не удалось сохранить проект: '+e.message);}}
  function exportPng(){if(gesture)finishGesture();const c=canvas();composite(context(c));c.toBlob(blob=>{if(!blob){tell('Не удалось экспортировать изображение.');return;}download(blob,baseName()+'.png');tell('PNG экспортирован. Для сохранения слоёв сохраните также проект.');},'image/png');}
  async function openProjectFile(file){if(!file||!safeReplace())return;try{fileNotice('Открываю проект…');if(file.size>100*1024*1024)throw Error('Проект слишком велик: предел 100 МБ.');const p=JSON.parse(await file.text());if(p.format!=='contour-studio'||p.version!==1)throw Error('Это не проект редактора «Контур» версии 1.');validateSize(p.width,p.height);if(!Array.isArray(p.layers)||!p.layers.length||p.layers.length>40||p.layers.length*p.width*p.height>MAX_LAYER_PIXELS)throw Error('В проекте слишком много слоёв.');const ids=new Set(),next=[];for(const l of p.layers){if(typeof l.id!=='string'||ids.has(l.id)||typeof l.name!=='string'||!Number.isFinite(l.opacity)||l.opacity<0||l.opacity>1||!BLENDS.includes(l.blend)||typeof l.png!=='string'||!l.png.startsWith('data:image/png;base64,'))throw Error('Повреждённые данные слоя.');ids.add(l.id);const image=await decodeUrl(l.png);if(image.naturalWidth!==p.width||image.naturalHeight!==p.height)throw Error('Размеры слоя не совпадают с холстом.');const c=canvas(p.width,p.height);context(c).drawImage(image,0,0);next.push({id:l.id,name:l.name.slice(0,120),visible:!!l.visible,locked:!!l.locked,opacity:l.opacity,blend:l.blend,canvas:c});}initialize(p.width,p.height,typeof p.name==='string'?p.name.slice(0,200):file.name,false);layers=next;layerCounter=Math.max(next.length,...next.map(l=>Number(l.id.replace('layer-',''))||0));activeId=ids.has(p.activeId)?p.activeId:next[next.length-1].id;started=true;$('welcome').hidden=true;render();renderLayers();fileNotice('');queueDraft();tell('Проект открыт. Слои восстановлены.');}catch(e){const message='Не удалось открыть проект: '+e.message;fileNotice(message,true);tell(message);}}
  const icons={
    brush:'M14 13 21 4c1-1 0-2-1-1l-9 7m3 3-3-3-3 3 3 3 3-3Z M9 15c-5-1-3 5-7 6 7 1 10-1 7-6Z',
    eraser:'m4 14 9-10a2 2 0 0 1 3 0l5 5a2 2 0 0 1 0 3l-8 9H9l-5-5a2 2 0 0 1 0-2Z M9 9l8 8 M12 21h10',
    fill:'m4 11 7-7 9 9-7 7-9-9Z M3 12h16 M8 2l5 5 M21 15s-3 3-3 5a3 3 0 0 0 6 0c0-2-3-5-3-5',
    wand:'m4 20 12-12 3 3L7 23 4 20Z M11 13l3 3 M4 3v4 M2 5h4 M19 2v4 M17 4h4 M21 16v4 M19 18h4',
    picker:'m14 6 4-4a2 2 0 0 1 3 3l-4 4 M12 4l8 8 M14 7 4 17v3h3L17 10 M4 20l-2 2',
    hand:'M8 12V5a2 2 0 0 1 4 0v6 M12 11V3a2 2 0 0 1 4 0v8 M16 11V5a2 2 0 0 1 4 0v10c0 5-3 7-7 7-3 0-5-2-7-5l-3-5a2 2 0 0 1 3-2l2 2',
    move:'M12 2v20 M2 12h20 M8 6l4-4 4 4 M8 18l4 4 4-4 M6 8l-4 4 4 4 M18 8l4 4-4 4',
    crop:'M6 2v16h16 M2 6h16v16 M10 6h8v8',
    file:'M14 2H5v20h14V7l-5-5Z M14 2v6h5 M8 14h8 M12 10v8',
    folder:'M2 7V4h7l3 3h10v14H2V7Z M2 10h20',
    undo:'M8 4 3 9l5 5 M3 9h10a7 7 0 0 1 0 14',
    redo:'m16 4 5 5-5 5 M21 9H11a7 7 0 0 0 0 14',
    edit:'m3 17 13-13 4 4L7 21H3v-4Z M14 6l4 4'
  };
  document.querySelectorAll('[data-icon]').forEach(el=>{const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','tool-icon');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',icons[el.dataset.icon]);path.setAttribute('fill','none');path.setAttribute('stroke','currentColor');path.setAttribute('stroke-width','1.7');path.setAttribute('stroke-linejoin','round');path.setAttribute('stroke-linecap','round');svg.append(path);el.prepend(svg);});
  function combineMode(e){return e.altKey?'subtract':e.shiftKey?'add':selectionCombine;}
  for(const mode of ['add','subtract'])$(mode+'Selection').onclick=()=>{selectionCombine=selectionCombine===mode?'replace':mode;for(const m of ['add','subtract'])$(m+'Selection').setAttribute('aria-pressed',String(selectionCombine===m));};
  function closeBrushMenu(){if(!$('brushMenu'))return;$('brushMenu').hidden=true;$('brushMenuButton').setAttribute('aria-expanded','false');}
  function positionMenu(menu,button){const r=button.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.right+8,window.innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(r.top,window.innerHeight-menu.offsetHeight-8))+'px';}
  let roundSize=20,squareSize=1,brushShape='round';
  $('brushMenuButton').onclick=()=>{closeColorSelectionMenu();const menu=$('brushMenu');menu.hidden=!menu.hidden;$('brushMenuButton').setAttribute('aria-expanded',String(!menu.hidden));if(!menu.hidden){positionMenu(menu,$('brushMenuButton'));menu.querySelector('[aria-checked="true"]').focus();}};
  $('brushMenu').querySelectorAll('[data-brush-shape]').forEach(b=>b.onclick=()=>{if(tool==='pencil')squareSize=Number($('brushSize').value);else if(tool==='brush')roundSize=Number($('brushSize').value);const square=b.dataset.brushShape==='square';brushShape=b.dataset.brushShape;$('brushSize').value=square?squareSize:roundSize;selectTool(square?'pencil':'brush');$('brushMenu').querySelectorAll('button').forEach(btn=>btn.setAttribute('aria-checked',String(btn===b)));viewport.focus({preventScroll:true});});
  document.addEventListener('pointerdown',e=>{if(!e.target.closest('#brushMenu,#brushMenuButton'))closeBrushMenu();},true);
  document.addEventListener('keydown',e=>{if($('brushMenu').hidden)return;if(e.code==='Escape'){closeBrushMenu();$('brushMenuButton').focus();e.preventDefault();e.stopImmediatePropagation();}else if(['ArrowDown','ArrowUp'].includes(e.code)){const a=[...$('brushMenu').querySelectorAll('button')],i=a.indexOf(document.activeElement);a[(i+(e.code==='ArrowDown'?1:-1)+a.length)%a.length].focus();e.preventDefault();e.stopImmediatePropagation();}});
  const blendDescriptions={'source-over':'Обычное: верхний слой закрывает нижние с учётом прозрачности.',multiply:'Умножение: затемняет цвета. Белое не меняет нижние слои; удобно для контура.',screen:'Экран: осветляет цвета. Чёрное не меняет нижние слои.',overlay:'Перекрытие: усиливает контраст, сохраняя светлые и тёмные участки.',darken:'Затемнение: выбирает более тёмные значения цветов двух слоёв.',lighten:'Осветление: выбирает более светлые значения цветов двух слоёв.'};
  function blendHint(){$('blendMode').title=blendDescriptions[$('blendMode').value];}
  [...$('blendMode').options].forEach(o=>o.title=blendDescriptions[o.value]);
  function openFile(file){if(!file)return;return /\.contour$/i.test(file.name)?openProjectFile(file):openImageFile(file);}
  function openSave(format='contour'){finishGesture();$('saveFormat').value=format;$('saveError').textContent='';saveDescription();$('saveDialog').showModal();}
  function saveDescription(){const f=$('saveFormat').value;$('jpegOptions').hidden=f!=='jpeg';$('saveDescription').textContent=f==='contour'?'Файл .contour сохраняет все слои для продолжения работы. Он загружается на Ваш компьютер; откройте его снова кнопкой «Открыть файл».':(f==='jpeg'?'JPEG сохраняет изображение без слоёв. Прозрачные участки станут белыми.':f==='tiff'?'TIFF сохраняет изображение с прозрачностью без слоёв, без сжатия.':'PNG сохраняет изображение с прозрачностью без слоёв.')+' Для продолжения работы со слоями сохраните также файл проекта .contour.';}
  $('saveFormat').onchange=saveDescription;$('jpegQuality').oninput=()=>$('jpegQualityOut').value=$('jpegQuality').value+'%';
  $('doSave').onclick=async()=>{const button=$('doSave');button.disabled=true;try{const f=$('saveFormat').value;if(f==='contour')saveProject();else{const c=canvas(),cc=context(c);composite(cc);if(f==='jpeg'){cc.save();cc.globalCompositeOperation='destination-over';cc.fillStyle='#fff';cc.fillRect(0,0,width,height);cc.restore();}let blob;if(f==='tiff')blob=new Blob([window.ContourFormats.encodeTiff(cc.getImageData(0,0,width,height))],{type:'image/tiff'});else blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Не удалось создать изображение.')),'image/'+f,Number($('jpegQuality').value)/100));download(blob,baseName()+'.'+(f==='jpeg'?'jpg':f==='tiff'?'tiff':'png'));}$('saveDialog').close();}catch(e){$('saveError').textContent=e.message;}finally{button.disabled=false;}};
  const basicColors=['#1e2429','#59616b','#9aa5b1','#e7e8e5','#ffffff','#ead09b','#c99358','#bd6152','#7a3c48','#b5869d','#7c68a4','#4e628a','#3f7f8a','#648b70','#9dad72','#ceb96d'];
  let palettes=[],paletteIndex=0,paletteEditing=null;
  function initializePalettes(){palettes=[{name:'Основная',colors:basicColors},{name:'Палитра 1 · Портрет',colors:['#fff2dd','#f4d7b7','#e6b991','#ce9575','#b67859','#965942','#744432','#4c2d27','#eec3bd','#ce8885','#a35c64','#6f3e4e','#ead4bf','#b8a598','#777074','#3c343a']},{name:'Палитра 2 · Океан',colors:['#f0fbfa','#d1eee9','#99d7d7','#60b8c6','#328fac','#236b91','#204e76','#183550','#0d2438','#147c80','#32958a','#69aea0','#a5c9b1','#d8d4ae','#b5a27c','#777b85']}];try{const saved=JSON.parse(localStorage.getItem('contour-palettes'));if(Array.isArray(saved)&&saved.length&&saved.length<=30&&saved.every(p=>typeof p.name==='string'&&p.name.length<=80&&Array.isArray(p.colors)&&p.colors.length>0&&p.colors.length<=64&&p.colors.every(c=>/^#[0-9a-f]{6}$/i.test(c))))palettes=saved;}catch{}renderPalettes();}
  function renderPalettes(){const select=$('paletteSelect');select.replaceChildren();palettes.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name;select.append(o);});select.value=paletteIndex;renderPalette();}
  function renderPalette(){$('palette').replaceChildren();for(const color of palettes[paletteIndex].colors){const b=document.createElement('button');b.style.background=color;b.dataset.color=color.toLowerCase();b.title=color;b.setAttribute('aria-label','Выбрать цвет '+color);b.onclick=()=>setColor(color);$('palette').append(b);}setColor($('color').value);}
  $('paletteSelect').onchange=()=>{paletteIndex=Number($('paletteSelect').value);renderPalette();};
  function editPalette(fresh){if(fresh&&palettes.length>=30){fileNotice('Можно сохранить до 30 палитр.',true);return;}paletteEditing={index:fresh?-1:paletteIndex,colors:fresh?[$('color').value]:palettes[paletteIndex].colors.slice()};$('paletteName').value=fresh?'Моя палитра':palettes[paletteIndex].name;renderPaletteEditor();$('paletteDialog').showModal();}
  function renderPaletteEditor(){$('paletteEditor').replaceChildren();paletteEditing.colors.forEach((color,i)=>{const row=document.createElement('div'),input=document.createElement('input'),remove=document.createElement('button');input.type='color';input.value=color;input.setAttribute('aria-label','Цвет '+(i+1));input.oninput=()=>paletteEditing.colors[i]=input.value;remove.type='button';remove.textContent='×';remove.title='Удалить цвет';remove.disabled=paletteEditing.colors.length===1;remove.onclick=()=>{paletteEditing.colors.splice(i,1);renderPaletteEditor();};row.append(input,remove);$('paletteEditor').append(row);});$('addPaletteColor').disabled=paletteEditing.colors.length>=64;}
  $('newPalette').onclick=()=>editPalette(true);$('editPalette').onclick=()=>editPalette(false);$('addPaletteColor').onclick=()=>{paletteEditing.colors.push($('color').value);renderPaletteEditor();};
  $('savePalette').onclick=()=>{const value={name:$('paletteName').value.trim().slice(0,80)||'Моя палитра',colors:paletteEditing.colors.slice()};if(paletteEditing.index<0){palettes.push(value);paletteIndex=palettes.length-1;}else palettes[paletteEditing.index]=value;try{localStorage.setItem('contour-palettes',JSON.stringify(palettes));}catch{fileNotice('Не удалось сохранить палитры в браузере.',true);}renderPalettes();$('paletteDialog').close();};
  function updateCropFields(){const b=cropBox;$('cropWidth').value=b?.w||width;$('cropHeight').value=b?.h||height;$('applyCrop').disabled=!b||b.w<1||b.h<1;$('dimensions').textContent=(b&&tool==='crop'?b.w+' × '+b.h:width+' × '+height)+' px';}
  function cropFromPoints(a,b){const sx=Math.max(0,Math.min(width-1,Math.floor(a.x))),sy=Math.max(0,Math.min(height-1,Math.floor(a.y))),dx=b.x>=sx?1:-1,dy=b.y>=sy?1:-1,availableW=dx>0?width-sx:sx,availableH=dy>0?height-sy:sy,r=Number($('cropRatio').value);let w=Math.max(1,Math.round(Math.abs(b.x-sx))),h=Math.max(1,Math.round(Math.abs(b.y-sy)));if(r){if(w/h>r)h=Math.max(1,Math.round(w/r));else w=Math.max(1,Math.round(h*r));const scale=Math.min(1,availableW/w,availableH/h);w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));}w=Math.min(w,availableW||1);h=Math.min(h,availableH||1);return{x:dx>0?sx:Math.max(0,sx-w),y:dy>0?sy:Math.max(0,sy-h),w,h};}
  function cropFields(axis){let b=cropBox||{x:0,y:0,w:width,h:height},w=Number($('cropWidth').value),h=Number($('cropHeight').value),r=Number($('cropRatio').value);if(!Number.isFinite(w)||!Number.isFinite(h))return;w=Math.round(Math.max(1,w));h=Math.round(Math.max(1,h));if(r){if(axis==='h')w=Math.round(h*r);else h=Math.round(w/r);}const scale=Math.min(1,(width-b.x)/w,(height-b.y)/h);w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));cropBox={x:b.x,y:b.y,w,h};updateCropFields();renderOverlay();}
  $('cropWidth').onchange=()=>cropFields('w');$('cropHeight').onchange=()=>cropFields('h');$('cropRatio').onchange=()=>{if(cropBox)cropFields('w');};$('cancelCrop').onclick=()=>{cropBox=null;updateCropFields();renderOverlay();};$('applyCrop').onclick=applyCrop;
  function applyCrop(){finishGesture();if(!cropBox)return;const b=cropBox;if(b.x===0&&b.y===0&&b.w===width&&b.h===height){cropBox=null;updateCropFields();renderOverlay();return;}const before=snapshot();layers.forEach(l=>{const c=canvas(b.w,b.h);context(c).drawImage(l.canvas,b.x,b.y,b.w,b.h,0,0,b.w,b.h);l.canvas=c;});width=b.w;height=b.h;cropBox=null;transformCache=null;setSelection(null);resizeDisplay();changed(before);updateCropFields();fit();}
  function alphaBox(data,mask){let x0=width,y0=height,x1=0,y1=0;for(let i=0;i<width*height;i++)if((!mask||mask[i])&&data[i*4+3]){const x=i%width,y=Math.floor(i/width);x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x+1);y1=Math.max(y1,y+1);}return x1>x0?{x:x0,y:y0,w:x1-x0,h:y1-y0}:null;}
  function prepareTransform(){if(transformCache?.layer===active())return transformCache;const l=active();if(!l||l.locked||!l.visible){transformCache=null;$('transformWidth').value=$('transformHeight').value='';$('applyTransform').disabled=true;return null;}const data=pixels(l.canvas),box=alphaBox(data.data,selection);if(!box){transformCache=null;$('transformWidth').value=$('transformHeight').value='';$('applyTransform').disabled=true;return null;}const base=canvas(),cut=canvas(),source=canvas(box.w,box.h);context(base).drawImage(l.canvas,0,0);const cutData=new Uint8ClampedArray(data.data),takeData=new Uint8ClampedArray(data.data.length);for(let i=0;i<width*height;i++){if(!selection||selection[i]){takeData.set(data.data.subarray(i*4,i*4+4),i*4);cutData.fill(0,i*4,i*4+4);}}context(cut).putImageData(new ImageData(cutData,width,height),0,0);const full=canvas();context(full).putImageData(new ImageData(takeData,width,height),0,0);context(source).drawImage(full,box.x,box.y,box.w,box.h,0,0,box.w,box.h);let maskSource=null;if(selection){maskSource=canvas(box.w,box.h);context(maskSource).drawImage(selectionCanvas(),box.x,box.y,box.w,box.h,0,0,box.w,box.h);}$('applyTransform').disabled=false;transformCache={layer:l,box,base,cut,source,maskSource};$('transformWidth').value=box.w;$('transformHeight').value=box.h;$('transformAngle').value=0;return transformCache;}
  function beginTransform(p,e){if(!editable())return;const t=prepareTransform();if(!t){tell('Слой пуст: перемещать нечего.');return;}const b=t.box,r=9/zoom,corners=[[b.x,b.y,'nw'],[b.x+b.w,b.y,'ne'],[b.x,b.y+b.h,'sw'],[b.x+b.w,b.y+b.h,'se']],hit=corners.find(([x,y])=>Math.hypot(x-p.x,y-p.y)<=r);gesture={...t,kind:'transform',before:snapshot(),original:{...b},box:{...b},start:p,handle:hit?.[2],angle:0,pointerId:e.pointerId};}
  function dragTransform(g,p){const o=g.original,dx=Math.round(p.x-g.start.x),dy=Math.round(p.y-g.start.y);if(!g.handle)g.box={...o,x:o.x+dx,y:o.y+dy};else{const west=g.handle.includes('w'),north=g.handle.includes('n');let w=Math.max(1,o.w+(west?-dx:dx)),h=Math.max(1,o.h+(north?-dy:dy));if($('keepAspect').checked){const ratio=o.w/o.h;if(Math.abs(w/o.w-1)>=Math.abs(h/o.h-1))h=Math.max(1,Math.round(w/ratio));else w=Math.max(1,Math.round(h*ratio));}g.box={x:west?o.x+o.w-w:o.x,y:north?o.y+o.h-h:o.y,w:Math.min(32768,w),h:Math.min(32768,h)};}previewTransform(g);}
  function transformedDraw(cc,source,b,angle){cc.save();cc.imageSmoothingEnabled=false;cc.translate(b.x+b.w/2,b.y+b.h/2);cc.rotate(angle*Math.PI/180);cc.drawImage(source,-b.w/2,-b.h/2,b.w,b.h);cc.restore();}
  function previewTransform(g){const cc=context(g.layer.canvas);cc.clearRect(0,0,width,height);cc.drawImage(g.cut,0,0);transformedDraw(cc,g.source,g.box,g.angle);$('transformWidth').value=g.box.w;$('transformHeight').value=g.box.h;render();}
  function commitTransform(g){const b=g.box,o=g.original||g.box;if(!g.angle&&b.x===o.x&&b.y===o.y&&b.w===o.w&&b.h===o.h){render();return;}if(g.maskSource){const maskCanvas=canvas();transformedDraw(context(maskCanvas),g.maskSource,b,g.angle);const data=pixels(maskCanvas).data;setSelection(Uint8Array.from({length:width*height},(_,i)=>Number(data[i*4+3]>=128)));}markLayerChanged(g.layer);changed(g.before);prepareTransform();renderOverlay();}
  function nudge(code,step){if(!editable())return;const t=prepareTransform();if(!t){tell('Слой пуст: перемещать нечего.');return;}const g={...t,before:snapshot(),original:{...t.box},box:{...t.box},angle:0};g.box.x+=code==='ArrowLeft'?-step:code==='ArrowRight'?step:0;g.box.y+=code==='ArrowUp'?-step:code==='ArrowDown'?step:0;previewTransform(g);commitTransform(g);}
  function constrainTransform(axis){const t=prepareTransform();if(!t||!$('keepAspect').checked)return;const ratio=t.box.w/t.box.h;if(axis==='w')$('transformHeight').value=Math.max(1,Math.round(Number($('transformWidth').value)/ratio));else $('transformWidth').value=Math.max(1,Math.round(Number($('transformHeight').value)*ratio));}
  $('transformWidth').onchange=()=>constrainTransform('w');$('transformHeight').onchange=()=>constrainTransform('h');
  $('applyTransform').onclick=()=>{if(!editable())return;const t=prepareTransform();if(!t)return;const w=Number($('transformWidth').value),h=Number($('transformHeight').value),angle=Number($('transformAngle').value);if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>32768||h>32768||!Number.isFinite(angle)||Math.abs(angle)>360){fileNotice('Укажите корректные размеры и угол поворота.',true);return;}const g={...t,original:{...t.box},box:{...t.box,w,h},angle,before:snapshot()};previewTransform(g);commitTransform(g);};

  document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));
  $('openImage').onclick=$('welcomeOpen').onclick=()=>$('imageInput').click();$('imageInput').onchange=e=>{openFile(e.target.files[0]);e.target.value='';};
  $('dismissFileNotice').onclick=()=>fileNotice('');

  $('newDoc').onclick=()=>$('newDialog').showModal();$('welcomeBlank').onclick=()=>{started=true;$('welcome').hidden=true;viewport.focus();queueDraft();};
  $('createDoc').onclick=()=>{try{const w=Number($('newWidth').value),h=Number($('newHeight').value);validateSize(w,h);if(!safeReplace())return;initialize(w,h,'Без названия',$('newWhite').checked);started=true;$('welcome').hidden=true;$('newDialog').close();$('newError').textContent='';queueDraft();tell('Новый холст создан.');}catch(e){$('newError').textContent=e.message;}};
  $('saveProject').onclick=()=>openSave();$('help').onclick=()=>$('helpDialog').showModal();$('undo').onclick=undo;$('redo').onclick=redo;
  $('zoomOut').onclick=()=>setZoom(zoom/1.25);$('zoomIn').onclick=()=>setZoom(zoom*1.25);$('zoom100').onchange=()=>setZoom(Number($('zoom100').value)/100);$('fit').onclick=fit;
  $('deselect').onclick=()=>setSelection(null);

  $('invertSelection').onclick=()=>{if(!selection)return;const mask=new Uint8Array(selection.length);for(let i=0;i<mask.length;i++)mask[i]=1-selection[i];setSelection(mask);};
  $('extractOutline').onclick=()=>$('outlineDialog').showModal();$('doExtract').onclick=extract;$('whitePoint').oninput=()=>{$('whitePointOut').value=$('whitePoint').value;};
  $('tolerance').onchange=refreshColorSelection;
  $('colorSelectionMenuButton').onclick=()=>{$('colorSelectionMenu').hidden?openColorSelectionMenu():closeColorSelectionMenu(true);};
  $('colorSelectionMenu').querySelectorAll('[data-selection-mode]').forEach(b=>b.onclick=()=>{setColorSelectionMode(b.dataset.selectionMode);selectTool('colorSelect');viewport.focus({preventScroll:true});tell((colorSelectionMode==='global'?'Весь цвет':'Одна область')+': щёлкните по рисунку. Shift — добавить, Alt — вычесть.');});
  document.addEventListener('pointerdown',e=>{if(!e.target.closest('#colorSelectionMenu,#colorSelectionMenuButton'))closeColorSelectionMenu();},true);
  window.addEventListener('resize',()=>closeColorSelectionMenu());
  $('addLayer').onclick=()=>{if(!canAdd())return;const s=snapshot(),l=layer();layers.splice(layers.indexOf(active())+1,0,l);activeId=l.id;changed(s);};
  $('duplicateLayer').onclick=()=>{if(!canAdd())return;const s=snapshot(),src=active(),l=layer(src.name+' — копия');Object.assign(l,{visible:src.visible,locked:src.locked,opacity:src.opacity,blend:src.blend});context(l.canvas).drawImage(src.canvas,0,0);layers.splice(layers.indexOf(src)+1,0,l);activeId=l.id;changed(s);};
  $('deleteLayer').onclick=()=>{if(layers.length<=1)return;if(active().locked){tell('Сначала снимите защиту слоя.');return;}const s=snapshot(),i=layers.indexOf(active());layers.splice(i,1);activeId=layers[Math.min(i,layers.length-1)].id;changed(s);};
  function reorder(delta){const i=layers.indexOf(active()),j=i+delta;if(j<0||j>=layers.length)return;const s=snapshot();[layers[i],layers[j]]=[layers[j],layers[i]];changed(s);}
  $('layerUp').onclick=()=>reorder(1);$('layerDown').onclick=()=>reorder(-1);
  $('layerOpacity').addEventListener('pointerdown',()=>{opacityBefore=snapshot();});$('layerOpacity').addEventListener('keydown',()=>{if(!opacityBefore)opacityBefore=snapshot();});
  $('layerOpacity').oninput=()=>{if(!opacityBefore)opacityBefore=snapshot();active().opacity=Number($('layerOpacity').value)/100;$('layerOpacityOut').value=$('layerOpacity').value+'%';render();};
  $('layerOpacity').onchange=()=>{if(opacityBefore){const s=opacityBefore;opacityBefore=null;changed(s);}};
  $('blendMode').onchange=()=>{const s=snapshot();active().blend=$('blendMode').value;changed(s);};
  $('brushSize').oninput=()=>updateToolCursor();
  $('brushOpacity').oninput=()=>{$('brushOpacityOut').value=$('brushOpacity').value+'%';};$('color').oninput=()=>setColor($('color').value);

  $('colorHex').onchange=()=>{let v=$('colorHex').value.trim();if(!v.startsWith('#'))v='#'+v;if(/^#[0-9a-f]{6}$/i.test(v))setColor(v);else{$('colorHex').value=$('color').value.toUpperCase();tell('Цвет вводится как #RRGGBB.');}};
  initializePalettes();setColor($('color').value);

  // Keep the canvas focus indicator for Tab navigation, not pointer painting.
  document.addEventListener('pointerdown',()=>viewport.classList.remove('keyboard-focus'),true);
  document.addEventListener('keydown',e=>{if(e.code==='Tab')viewport.classList.add('keyboard-focus');},true);
  document.addEventListener('keydown',e=>{
    if(document.querySelector('dialog[open]')||!$('brushMenu').hidden)return;
    if(!$('colorSelectionMenu').hidden){
      if(e.code==='Escape'){closeColorSelectionMenu(true);e.preventDefault();}
      else if(['ArrowDown','ArrowUp','Home','End'].includes(e.code)){const options=[...$('colorSelectionMenu').querySelectorAll('[data-selection-mode]')],i=options.indexOf(document.activeElement),next=e.code==='Home'?0:e.code==='End'?options.length-1:(i+(e.code==='ArrowDown'?1:-1)+options.length)%options.length;options[next].focus();e.preventDefault();}
      else if(e.code==='Tab')closeColorSelectionMenu();
      return;
    }
    if(e.target.closest('input,textarea,select,[contenteditable=true]'))return;
    if(e.code==='KeyR'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){if(!eraseHeld){finishGesture();eraseHeld=true;refreshTool();}e.preventDefault();return;}
    if((e.code==='AltLeft'||e.code==='AltRight')&&!e.ctrlKey&&!e.metaKey){if(gesture)finishGesture();altPicker=true;refreshTool();if(temporaryPicker())e.preventDefault();return;}
    const mod=e.ctrlKey||e.metaKey;let handled=true;if(gesture&&e.code!=='Space'&&e.code!=='Escape')finishGesture();
    if(mod){switch(e.code){case 'KeyZ':e.shiftKey?redo():undo();break;case 'KeyY':redo();break;case 'KeyO':$('imageInput').click();break;case 'KeyS':openSave(e.shiftKey?'png':'contour');break;case 'KeyC':copyPixels();break;case 'KeyX':copyPixels(true);break;case 'KeyV':pastePixels();break;case 'KeyT':selectTool('move');break;case 'KeyA':setSelection(new Uint8Array(width*height).fill(1));break;case 'KeyD':setSelection(null);break;case 'KeyJ':copySelection(e.shiftKey);break;default:handled=false;}}
    else if(!e.altKey){const tools={KeyB:'brush',KeyE:'eraser',KeyG:'fill',KeyW:'colorSelect',KeyM:'rect',KeyL:'lasso',KeyC:'crop',KeyV:'move',KeyI:'picker',KeyH:'pan'};if(tools[e.code])selectTool(tools[e.code]);else switch(e.code){case 'Space':space=true;break;case 'Enter':if(tool==='crop')applyCrop();else handled=false;break;case 'ArrowLeft':case 'ArrowRight':case 'ArrowUp':case 'ArrowDown':if(tool==='move')nudge(e.code,e.shiftKey?10:1);else handled=false;break;case 'Escape':if(gesture)finishGesture(true);else if(tool==='crop'){cropBox=null;updateCropFields();renderOverlay();}else setSelection(null);break;case 'Delete':case 'Backspace':deletePixels();break;case 'BracketLeft':{const size=$('brushSize');size.value=Math.max(1,Number(size.value)-(tool==='pencil'?1:5));break;}case 'BracketRight':{const size=$('brushSize');size.value=Math.min(500,Number(size.value)+(tool==='pencil'?1:5));break;}case 'F1':$('helpDialog').showModal();break;default:handled=false;}}
    else handled=false;
    if(handled){e.preventDefault();updateToolCursor();}
  });
  document.addEventListener('keyup',e=>{if(e.code==='KeyR'&&eraseHeld){finishGesture();eraseHeld=false;refreshTool();}if(e.code==='AltLeft'||e.code==='AltRight'){altPicker=e.altKey;refreshTool();}if(e.code==='Space'){space=false;updateToolCursor();}});
  window.addEventListener('beforeunload',e=>{if(revision!==savedRevision){e.preventDefault();e.returnValue='';}});
  viewport.addEventListener('dragover',e=>{e.preventDefault();});viewport.addEventListener('drop',e=>{e.preventDefault();const f=e.dataTransfer.files[0];openFile(f);});
  initialize(960,720,'Без названия');setColorSelectionMode('region',false);selectTool('brush');findDraft();
})();
