const assert=require('node:assert/strict');
const {harness,settle,runTimer,native}=require('./harness.cjs');
const click=(h,id)=>h.d.getElementById(id).click();
function value(h,id,v,event='change'){const el=h.d.getElementById(id);el.value=v;el.dispatchEvent(new h.w.Event(event,{bubbles:true}));}
function tool(h,t){if(['rect','lasso'].includes(t))h.d.querySelector(`[data-selection-mode="${t}"]`).click();else if(['line','curve'].includes(t))h.d.querySelector(`[data-path-tool="${t}"]`).click();else h.d.querySelector(`[data-tool="${t}"]`).click();}
function blank(h,w=100,height=80){click(h,'newDoc');value(h,'newWidth',w);value(h,'newHeight',height);click(h,'createDoc');h.flushFrames();value(h,'zoom100',100);}
const px=(h,x,y)=>[...h.image().subarray((y*h.d.getElementById('display').width+x)*4,(y*h.d.getElementById('display').width+x)*4+4)];
const white=[255,255,255,255],red=[189,97,82,255],blue=[18,52,86,255];
function square(h,n=1){h.d.querySelector('[data-brush-shape="square"]').click();value(h,'brushSize',n,'input');}
async function choose(h,id,file){const input=h.d.getElementById(id);Object.defineProperty(input,'files',{configurable:true,value:[file]});input.dispatchEvent(new h.w.Event('change'));await settle();for(let i=0;i<100&&/^(Добавляю|Открываю)/.test(h.d.getElementById('fileNoticeText').textContent);i++)await new Promise(r=>setTimeout(r,10));}
async function project(h){click(h,'saveProject');click(h,'doSave');await settle();return JSON.parse(await h.w.testDownloads.at(-1).blob.text());}
async function layerPixels(p,i){const image=await native.loadImage(Buffer.from(p.layers[i].png.split(',')[1],'base64')),c=native.createCanvas(p.width,p.height);c.getContext('2d').drawImage(image,0,0);return c.getContext('2d').getImageData(0,0,p.width,p.height).data;}
function png(w,height,color){const c=native.createCanvas(w,height),ctx=c.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,w,height);const b=new Blob([c.toBuffer('image/png')],{type:'image/png'});b.name='reference.png';return b;}
(async()=>{
 let h=harness();blank(h);h.event('pointermove',20,20);assert.equal(h.d.getElementById('toolCursor').style.backgroundColor,'rgb(189, 97, 82)');assert.equal(h.d.getElementById('toolCursor').style.opacity,'1');square(h,4);h.event('pointermove',20,20);assert.equal(h.d.getElementById('toolCursor').classList.contains('round'),false);
 click(h,'themeToggle');assert.equal(h.d.documentElement.dataset.theme,'light');assert.equal(h.w.localStorage.getItem('contour-theme'),'light');assert.match(h.d.getElementById('themeToggle').title,/Тёмная/);click(h,'themeToggle');assert.equal(h.d.documentElement.dataset.theme,'dark');
 const presets=h.w.localStorage.getItem('contour-palettes'),presetCount=h.d.getElementById('paletteSelect').options.length;click(h,'newPalette');assert.equal(h.d.querySelectorAll('#paletteEditor .empty-slot').length,20);value(h,'paletteName','Мои цвета');value(h,'paletteHex','123456','input');click(h,'applyPaletteColor');h.d.querySelectorAll('#paletteEditor button')[1].click();click(h,'addPaletteColor');h.d.querySelectorAll('#paletteEditor button')[2].click();value(h,'paletteColorInput','#00ff00','input');value(h,'paletteHue',240,'input');assert.equal(h.d.getElementById('paletteHex').value,'#0000FF');click(h,'applyPaletteColor');h.d.querySelectorAll('#paletteEditor button')[3].click();const field=h.d.getElementById('paletteColorField');field.getBoundingClientRect=()=>({left:0,top:0,width:200,height:100});field.dispatchEvent(new h.w.MouseEvent('pointerdown',{clientX:100,clientY:50,bubbles:true}));assert.equal(h.d.getElementById('paletteHex').value,'#404080');click(h,'applyPaletteColor');click(h,'savePalette');const palettes=JSON.parse(h.w.localStorage.getItem('contour-palettes'));assert.equal(palettes.length,presetCount+1);assert.deepEqual(palettes.at(-1).colors.slice(0,5),['#123456','#bd6152','#0000ff','#404080',null]);assert.equal(palettes[0].colors[0],'#1e2429');assert.equal(presets,null);
 
 // Import different sizes as independent layers; one undo also restores automatic expansion.
 square(h);h.stroke([[10,10]]);const original=h.image();await choose(h,'layerImageInput',png(20,10,'#123456'));assert.equal(h.d.querySelectorAll('.layer-row').length,3);assert.deepEqual(px(h,10,10),red);assert.deepEqual(px(h,40,35),blue);click(h,'undo');assert.ok(h.image().equals(original));await choose(h,'layerImageInput',png(120,20,'#123456'));assert.equal(h.d.getElementById('display').width,120,h.d.getElementById('fileNoticeText').textContent);assert.deepEqual(px(h,10,10),red);assert.deepEqual(px(h,110,75),white);click(h,'undo');assert.ok(h.image().equals(original));
 
 // Canvas dimensions preserve actual pixels and alpha, support anchors and edge dragging.
 click(h,'resizeCanvas');value(h,'canvasWidth',140);value(h,'canvasHeight',100);value(h,'canvasAnchor','center');click(h,'applyCanvasSize');value(h,'zoom100',100);assert.deepEqual(px(h,30,20),red);assert.deepEqual(px(h,10,10),white);let p=await project(h);assert.equal((await layerPixels(p,0))[(99*140+139)*4+3],255);assert.equal((await layerPixels(p,1))[(99*140+139)*4+3],0);click(h,'undo');assert.ok(h.image().equals(original));tool(h,'pan');const edge=h.d.querySelector('[data-canvas-edge="se"]');const edgeEvent=new h.w.MouseEvent('pointerdown',{bubbles:true,clientX:100,clientY:80});Object.defineProperty(edgeEvent,'pointerId',{value:1});edge.dispatchEvent(edgeEvent);h.event('pointermove',130,100);assert.equal(h.d.getElementById('dimensions').textContent,'130 × 100 px');h.event('pointerup',130,100);assert.equal(h.d.getElementById('display').width,130);assert.deepEqual(px(h,10,10),red);click(h,'undo');h.w.close();
 
 // Live rotation, cancel, one-step undo and a rotation handle outside the canvas.
 h=harness();blank(h);square(h,1);h.stroke([[35,40],[64,40]]);const straight=h.image();tool(h,'move');value(h,'transformAngle',90,'input');assert.notDeepEqual(h.image(),straight);assert.deepEqual(px(h,35,40),white);click(h,'cancelTransform');assert.ok(h.image().equals(straight));value(h,'transformAngle',90,'input');click(h,'applyTransform');const rotated=h.image();assert.notDeepEqual(rotated,straight);click(h,'undo');assert.ok(h.image().equals(straight));click(h,'redo');assert.ok(h.image().equals(rotated));click(h,'undo');tool(h,'brush');square(h);h.stroke([[50,1]]);tool(h,'move');const handleX=parseFloat(h.d.getElementById('rotationHandle').style.left),handleY=parseFloat(h.d.getElementById('rotationHandle').style.top),beforeDrag=h.image();h.stroke([[handleX,handleY],[handleX+30,handleY+30]]);assert.ok(!h.image().equals(beforeDrag));click(h,'undo');assert.ok(h.image().equals(beforeDrag));assert.equal(h.d.getElementById('rotationHandle').hidden,false);assert.ok(parseFloat(h.d.getElementById('rotationHandle').style.top)<0);h.w.close();
 
 // Binary mask prevents brush, fill, delete and transform from changing other pixels.
 let stored;const store={read:async()=>stored||null,write:async p=>stored=p};h=harness(store);await settle();blank(h);square(h,20);h.stroke([[35,40],[64,40]]);tool(h,'rect');h.stroke([[30,30],[50,50]]);click(h,'maskFromSelection');click(h,'deselect');value(h,'color','#123456','input');square(h,10);h.stroke([[35,40],[65,40]]);assert.deepEqual(px(h,35,40),blue);assert.deepEqual(px(h,60,40),red);tool(h,'fill');value(h,'color','#00ff00','input');h.stroke([[60,40]]);assert.deepEqual(px(h,60,40),red);h.key('keydown','KeyA',{ctrlKey:true});h.key('keydown','Delete');assert.deepEqual(px(h,35,40),white);assert.deepEqual(px(h,60,40),red);click(h,'undo');click(h,'deselect');tool(h,'move');value(h,'transformAngle',90,'input');assert.deepEqual(px(h,60,40),red);click(h,'cancelTransform');tool(h,'brush');await runTimer(h);assert.equal(stored.version,2);assert.ok(stored.layers.some(l=>l.mask));p=await project(h);assert.equal(p.version,2);assert.ok(p.layers[1].mask);assert.equal(p.layers[1].maskEnabled,true);const expected=h.image();const recovered=harness(store);await settle();click(recovered,'restoreDraft');await settle();for(let i=0;i<100&&recovered.d.getElementById('restoreDraft').disabled;i++)await new Promise(r=>setTimeout(r,10));assert.ok(recovered.image().equals(expected));assert.equal(recovered.d.querySelector('.layer-row.active .mask-button').getAttribute('aria-pressed'),'true');const reopened=harness();blank(reopened);await choose(reopened,'imageInput',{name:'masked.contour',text:async()=>JSON.stringify(p)});assert.ok(reopened.d.getElementById('projectPreviewDialog').hasAttribute('open'));click(reopened,'confirmProjectPreview');assert.ok(reopened.image().equals(expected));assert.equal(reopened.d.querySelector('.layer-row.active .mask-button').getAttribute('aria-pressed'),'true');
 click(h,'resizeCanvas');value(h,'canvasWidth',120);value(h,'canvasHeight',100);value(h,'canvasAnchor','center');click(h,'applyCanvasSize');h.flushFrames();value(h,'zoom100',100);square(h,1);value(h,'color','#000000','input');h.stroke([[45,50]]);assert.deepEqual(px(h,45,50),[0,0,0,255]);h.stroke([[70,50]]);assert.deepEqual(px(h,70,50),red);click(h,'undo');click(h,'undo');click(h,'undo');assert.ok(h.image().equals(expected));h.w.close();recovered.w.close();reopened.w.close();
 
 // Straight line and Bézier preview redraw from original tiles: hard edges, uniform opacity, cancel and undo.
 h=harness();blank(h);value(h,'brushSize',1,'input');tool(h,'line');h.stroke([[10,10],[80,10]]);assert.deepEqual(px(h,50,10),red);assert.deepEqual(px(h,50,11),white);click(h,'undo');assert.deepEqual(px(h,50,10),white);value(h,'brushSize',7,'input');h.stroke([[10,10],[80,50]]);for(let i=0,data=h.image();i<data.length;i+=4)assert.ok((data[i]===255&&data[i+1]===255&&data[i+2]===255)||(data[i]===189&&data[i+1]===97&&data[i+2]===82));click(h,'undo');tool(h,'curve');h.stroke([[10,40]]);h.stroke([[90,40]]);assert.equal(h.d.getElementById('applyPath').disabled,false);const initial=h.image();h.stroke([[37,40],[35,5]]);assert.notDeepEqual(h.image(),initial);h.key('keydown','Escape');assert.deepEqual(px(h,50,40),white);h.stroke([[10,40]]);h.stroke([[90,40]]);h.stroke([[37,40],[35,5]]);h.stroke([[63,40],[65,75]]);const curve=h.image();h.key('keydown','Enter');assert.ok(h.image().equals(curve));click(h,'undo');for(let i=0,data=h.image();i<data.length;i+=4)assert.deepEqual([...data.subarray(i,i+4)],white);click(h,'redo');assert.ok(h.image().equals(curve));
 h.key('keydown','KeyU');assert.equal(h.d.getElementById('pathOptions').hidden,true);tool(h,'crop');click(h,'cropRatioButton');const portrait=h.d.querySelector('[data-crop-ratio="0.6666666667"]')||[...h.d.querySelectorAll('[data-crop-ratio]')].find(e=>e.textContent==='2:3');assert.ok(portrait);const rect=portrait.querySelector('rect');assert.ok(Number(rect.getAttribute('height'))>Number(rect.getAttribute('width')));assert.equal(h.d.querySelector('[data-crop-ratio="1"]').textContent,'1:1');h.w.close();
 console.log('Features verified: filled brush footprint, themes, empty palette slots/HEX/HSV, layer import and expansion undo, canvas alpha/anchor/handles, live rotation/cancel, edit masks and project/draft/resize roundtrip, hard lines and adjustable Bézier undo/cancel, crop orientation icons.');
})().catch(e=>{console.error(e);process.exitCode=1});
