const assert=require('node:assert/strict'),{harness,settle}=require('./harness.cjs');
const column=(h,x,y)=>{const image=h.back(h.d.getElementById('display')).getContext('2d').getImageData(x,y-50,1,100).data;let n=0;for(let i=0;i<image.length;i+=4)if(image[i]<80)n++;return n;};
function drawPressure(h,square=false){h.d.getElementById('welcomeBlank').click();if(square)h.d.querySelector('[data-brush-shape="square"]').click();h.d.getElementById('brushSize').value=50;h.d.getElementById('color').value='#112233';h.event('pointerdown',100,150,{pointerType:'pen',pressure:.1});for(let x=110;x<=350;x+=10)h.event('pointermove',x,150,{pointerType:'pen',pressure:.1+.8*(x-100)/250});h.event('pointerup',350,150,{pointerType:'pen',pressure:0});h.flushFrames();}
(async()=>{
 for(const square of [false,true]){const h=harness();const before=h.image();drawPressure(h,square);assert.ok(column(h,310,150)>column(h,115,150)+10,'pen pressure must widen '+(square?'square':'round')+' brush');const image=h.image();for(let i=0;i<image.length;i+=4)assert.ok(image[i]===255||image[i]===17,'opaque pressure brush must keep exact colors');h.d.getElementById('undo').click();assert.deepEqual(h.image(),before);h.d.getElementById('redo').click();assert.deepEqual(h.image(),image);h.w.close();}
 for(const pointerType of ['mouse','touch','pen']){const h=harness();h.d.getElementById('welcomeBlank').click();h.d.getElementById('brushSize').value=50;h.d.getElementById('color').value='#112233';h.stroke([[100,150],[250,150],[350,150]],{pointerType,pressure:.5});assert.ok(column(h,150,150)>=48,'constant unsupported pressure falls back to full size');h.w.close();}
 const h=harness(undefined,[{name:'Портрет пользователя',colors:['#123456',null]}],{settings:{layout:'mobile'}}),d=h.d;assert.equal(d.documentElement.dataset.layout,'mobile');d.getElementById('welcomeBlank').click();h.d.getElementById('color').value='#112233';h.stroke([[70,80],[120,80]],{pointerType:'mouse'});const before=h.image(),revision=h.w.ContourEditor.state().revision;
 h.event('pointerdown',200,200,{pointerType:'touch',pointerId:1});h.event('pointermove',220,200,{pointerType:'touch',pointerId:1});h.event('pointerdown',300,200,{pointerType:'touch',pointerId:2});assert.deepEqual(h.image(),before,'second finger cancels only uncommitted stroke');h.event('pointermove',350,200,{pointerType:'touch',pointerId:2});assert.ok(h.w.ContourEditor.state().zoom>1);h.event('pointerup',350,200,{pointerType:'touch',pointerId:2});h.event('pointerup',220,200,{pointerType:'touch',pointerId:1});assert.equal(h.w.ContourEditor.state().revision,revision);h.d.getElementById('undo').click();assert.ok(h.w.ContourEditor.state().revision<revision,'previous stroke remains undoable');
 d.getElementById('mobileColor').click();assert.equal(d.querySelector('.color-panel').parentElement.id,'mobilePanel');d.getElementById('mobileLayers').click();assert.equal(d.querySelector('.layer-panel').parentElement.id,'mobilePanel');assert.equal(d.querySelector('.color-panel').parentElement.className,'sidebar');d.getElementById('panelClose').click();assert.equal(d.querySelector('.layer-panel').parentElement.className,'sidebar');
 d.getElementById('settingsButton').click();d.getElementById('settingLanguage').value='en';d.getElementById('settingLanguage').dispatchEvent(new h.w.Event('change'));await settle();assert.equal(d.documentElement.lang,'en');assert.equal(d.getElementById('newDoc').title,'New sheet');assert.equal(d.getElementById('settingsButton').title,'Settings');assert.equal(d.getElementById('paletteSelect').options[0].textContent,'Портрет пользователя');assert.equal(d.getElementById('canvasPreset').options[0].textContent,'Custom size');
 d.getElementById('settingLayout').value='desktop';d.getElementById('settingLayout').dispatchEvent(new h.w.Event('change'));assert.equal(d.documentElement.dataset.layout,'desktop');assert.equal(JSON.parse(h.w.localStorage.getItem('contour-settings')).layout,'desktop');h.w.ContourI18n.setLanguage('ru');await settle();assert.equal(d.getElementById('newDoc').title,'Новый лист');assert.equal(d.getElementById('settingsButton').title,'Настройки');h.w.close();
 const curve=harness(undefined,undefined,{settings:{layout:'mobile'}});curve.d.getElementById('welcomeBlank').click();curve.w.ContourEditor.selectTool('curve',true);curve.stroke([[120,140],[150,160]]);curve.stroke([[260,220],[300,240]]);const curveBefore=curve.image(),curveRevision=curve.w.ContourEditor.state().revision;assert.equal(curve.w.ContourEditor.state().curve,true);curve.d.getElementById('settingsButton').dispatchEvent(new curve.w.MouseEvent('pointerdown',{bubbles:true}));curve.d.getElementById('settingsButton').click();assert.equal(curve.w.ContourEditor.state().curve,true,'opening settings cannot apply a curve');curve.d.getElementById('settingLayout').value='desktop';curve.d.getElementById('settingLayout').dispatchEvent(new curve.w.Event('change'));curve.d.getElementById('settingLanguage').value='en';curve.d.getElementById('settingLanguage').dispatchEvent(new curve.w.Event('change'));await settle();assert.equal(curve.w.ContourEditor.state().curve,true);assert.equal(curve.w.ContourEditor.state().revision,curveRevision);assert.deepEqual(curve.image(),curveBefore);curve.w.close();
 const opacity=harness(undefined,undefined,{settings:{pressure:'opacity'}});opacity.d.getElementById('newWhite').checked=false;opacity.d.getElementById('createDoc').click();opacity.d.getElementById('brushSize').value=30;opacity.d.getElementById('color').value='#112233';opacity.event('pointerdown',150,150,{pointerType:'pen',pressure:.2});opacity.event('pointerup',150,150,{pointerType:'pen',pressure:0});const alpha=opacity.back(opacity.d.getElementById('display')).getContext('2d').getImageData(150,150,1,1).data;assert.ok(alpha[3]>=48&&alpha[3]<=55,'opacity pressure must retain intentional opacity');opacity.w.close();
 const firstEnglish=harness(undefined,undefined,{settings:{language:'en'}});await settle();firstEnglish.w.ContourI18n.setLanguage('ru');await settle();assert.equal(firstEnglish.d.getElementById('cropRatioButton').textContent,'Свободно ▾');assert.equal(firstEnglish.d.getElementById('settingsButton').title,'Настройки');firstEnglish.w.close();
 console.log('Mobile and pressure: round/square variable width with exact colors, fallback, undo/redo, two-finger cancellation and zoom, panel restoration, manual layout, EN/RU and custom names verified.');
})().catch(e=>{console.error(e);process.exitCode=1;});
