const assert=require('node:assert/strict'),fs=require('node:fs');
const {harness,settle,runTimer,native}=require('./harness.cjs');
const C=require('../core.js'),F=require('../formats.js');
const pixel=(h,x,y)=>{const w=h.d.getElementById('display').width;return [...h.image().subarray((y*w+x)*4,(y*w+x)*4+4)];};
const click=(h,id)=>h.d.getElementById(id).click(), tool=(h,v)=>{if(v==='rect'||v==='lasso')h.d.querySelector('[data-selection-mode="'+v+'"]').click();else h.d.querySelector('[data-tool="'+v+'"]').click();};
const value=(h,id,v,ev='change')=>{const el=h.d.getElementById(id);el.value=v;el.dispatchEvent(new h.w.Event(ev,{bubbles:true}));};
function blank(h){click(h,'welcomeBlank');value(h,'zoom100',100);}
function square(h,size=1){h.d.querySelector('[data-brush-shape="square"]').click();h.d.getElementById('brushSize').value=size;}
function shape(h,points,color,size=1){square(h,size);h.d.getElementById('color').value=color;h.stroke(points);}
(async()=>{
 const h=harness(),d=h.d;blank(h);
 assert.equal(d.querySelectorAll('.tools [data-tool]').length,9);assert.equal(d.querySelector('[data-tool="pencil"]'),null);assert.equal(d.getElementById('brushAntialias'),null);assert.equal(d.getElementById('sampleSource'),null);assert.equal(d.getElementById('toggleSelectionOutline'),null);assert.equal(d.querySelector('.sidebar-note'),null);
 assert.equal(d.getElementById('toleranceControl').hidden,true);tool(h,'colorSelect');assert.equal(d.getElementById('drawingOptions').hidden,true);assert.equal(d.getElementById('opacityOptions').hidden,true);assert.equal(d.getElementById('toleranceControl').hidden,false);tool(h,'picker');assert.equal(d.getElementById('toleranceControl').hidden,true);
 // Opaque round edges, square stamps, cursor color and temporary tool restoration.
 tool(h,'brush');d.getElementById('color').value='#bd6152';d.getElementById('brushSize').value=17;h.stroke([[100,100],[150,135],[220,110]]);const painted=h.image();for(let i=0;i<painted.length;i+=4)assert.ok((painted[i]===255&&painted[i+1]===255&&painted[i+2]===255)||(painted[i]===189&&painted[i+1]===97&&painted[i+2]===82),'no partially blended brush edges');
 h.key('keydown','AltLeft',{altKey:true});assert.equal(d.querySelector('[data-tool].selected').dataset.tool,'picker');h.stroke([[100,100]],{altKey:true});assert.equal(d.getElementById('color').value,'#bd6152');assert.deepEqual(h.image(),painted);h.key('keyup','AltLeft');assert.equal(d.querySelector('[data-tool].selected').dataset.tool,'brush');
 tool(h,'fill');h.key('keydown','KeyR');assert.equal(d.querySelector('[data-tool].selected').dataset.tool,'eraser');h.stroke([[100,100]]);assert.deepEqual(pixel(h,100,100),[255,255,255,255]);h.key('keyup','KeyR');assert.equal(d.querySelector('[data-tool].selected').dataset.tool,'fill');click(h,'undo');assert.deepEqual(h.image(),painted);
 square(h);d.getElementById('color').value='#000000';h.stroke([[400,200],[410,200]]);assert.deepEqual(pixel(h,405,200),[0,0,0,255]);assert.deepEqual(pixel(h,405,201),[255,255,255,255]);h.event('pointermove',405,200);assert.equal(d.getElementById('toolCursor').classList.contains('round'),false);assert.equal(d.getElementById('toolCursor').style.width,'1px');
 // Local versus global, persistent +/- and standard clipboard on selected pixels.
 for(const x of [300,500])shape(h,[[x,300],[x+40,300],[x+40,340],[x,340],[x,300]],'#000000');
 tool(h,'colorSelect');h.stroke([[320,320]]);const local=d.querySelector('#selectionOutline path').getAttribute('d');assert.equal(local,'M301 301H340V340H301V301Z');
 click(h,'addSelection');h.stroke([[520,320]]);const union=d.querySelector('#selectionOutline path').getAttribute('d');assert.ok(union.includes('501 301'));click(h,'subtractSelection');h.stroke([[320,320]]);assert.equal(d.querySelector('#selectionOutline path').getAttribute('d'),'M501 301H540V340H501V301Z');click(h,'subtractSelection');
 d.querySelector('[data-selection-mode="global"]').click();h.stroke([[320,320]]);assert.notEqual(d.querySelector('#selectionOutline path').getAttribute('d'),local);d.querySelector('[data-selection-mode="region"]').click();h.stroke([[320,320]]);
 // White was on paper only, so paint a solid block into active layer for copy/cut.
 click(h,'deselect');shape(h,[[700,400],[709,400]],'#3f7f8a',10);tool(h,'rect');h.stroke([[695,395],[710,405]]);const beforeCut=h.image(),layersBefore=d.querySelectorAll('.layer-row').length;h.key('keydown','KeyC',{ctrlKey:true});assert.equal(d.querySelectorAll('.layer-row').length,layersBefore);h.key('keydown','KeyX',{ctrlKey:true});assert.deepEqual(pixel(h,700,400),[255,255,255,255]);h.key('keydown','KeyV',{ctrlKey:true});assert.equal(d.querySelectorAll('.layer-row').length,layersBefore+1);assert.deepEqual(h.image(),beforeCut);click(h,'undo');assert.equal(d.querySelectorAll('.layer-row').length,layersBefore);click(h,'undo');assert.deepEqual(h.image(),beforeCut);
 // Lasso uses a hard pixel mask, supports subtraction and Delete with undo.
 tool(h,'lasso');h.stroke([[680,380],[740,380],[740,430],[680,430],[680,380]]);assert.ok(d.querySelector('#selectionOutline path').getAttribute('d'));const beforeDelete=h.image();h.key('keydown','Delete');assert.notDeepEqual(h.image(),beforeDelete);click(h,'undo');assert.deepEqual(h.image(),beforeDelete);assert.equal(d.getElementById('selectionOutline').hasAttribute('hidden'),false);h.w.close();
 // Transform exact arrow offsets, independent scaling and selected-region preservation.
 const t=harness();blank(t);shape(t,[[100,100],[109,100]],'#bd6152',1);shape(t,[[200,200]],'#3f7f8a',1);tool(t,'rect');t.stroke([[99,99],[111,102]]);tool(t,'move');t.key('keydown','ArrowRight');assert.deepEqual(pixel(t,100,100),[255,255,255,255]);assert.deepEqual(pixel(t,110,100),[189,97,82,255]);assert.deepEqual(pixel(t,200,200),[63,127,138,255]);t.key('keydown','ArrowDown',{shiftKey:true});assert.deepEqual(pixel(t,110,110),[189,97,82,255]);click(t,'undo');click(t,'undo');assert.deepEqual(pixel(t,100,100),[189,97,82,255]);
 t.d.getElementById('keepAspect').checked=false;value(t,'transformWidth',20);value(t,'transformHeight',2);click(t,'applyTransform');assert.deepEqual(pixel(t,119,101),[189,97,82,255]);assert.deepEqual(pixel(t,120,101),[255,255,255,255]);assert.deepEqual(pixel(t,200,200),[63,127,138,255]);click(t,'undo');assert.deepEqual(pixel(t,109,100),[189,97,82,255]);
 t.event('pointerdown',105,100);t.event('pointermove',135,130);t.key('keydown','Escape');assert.deepEqual(pixel(t,100,100),[189,97,82,255]);assert.deepEqual(pixel(t,135,130),[255,255,255,255]);t.w.close();
 // Crop all layers, update dimensions live, undo structural resize then pixel history.
 const c=harness();blank(c);shape(c,[[100,100]],'#bd6152',1);const original=c.image();tool(c,'crop');value(c,'cropRatio',1);c.event('pointerdown',50,50);c.event('pointermove',250,170);assert.equal(c.d.getElementById('dimensions').textContent,'200 × 200 px');c.event('pointerup',250,170);c.key('keydown','Enter');assert.equal(c.d.getElementById('display').width,200);assert.deepEqual(pixel(c,50,50),[189,97,82,255]);click(c,'undo');assert.equal(c.d.getElementById('display').width,960);assert.deepEqual(c.image(),original);click(c,'redo');assert.equal(c.d.getElementById('display').height,200);value(c,'zoom100',100);square(c);c.stroke([[20,20]]);click(c,'undo');assert.deepEqual(pixel(c,20,20),[255,255,255,255]);click(c,'undo');assert.deepEqual(c.image(),original);c.w.close();
 // Remove white background: only one extra layer and actual transparent white.
 const b=harness();blank(b);tool(b,'fill');b.d.getElementById('color').value='#ffffff';b.stroke([[10,10]]);shape(b,[[50,50],[90,50]],'#000000',1);const n=b.d.querySelectorAll('.layer-row').length;click(b,'extractOutline');click(b,'doExtract');assert.equal(b.d.querySelectorAll('.layer-row').length,n+1);assert.deepEqual(pixel(b,10,10),[0,0,0,0]);assert.deepEqual(pixel(b,70,50),[0,0,0,255]);click(b,'undo');assert.deepEqual(pixel(b,10,10),[255,255,255,255]);
 // Palette naming and locally saved color edits.
 const presetCount=b.d.getElementById('paletteSelect').options.length;assert.ok(presetCount>10);value(b,'paletteSelect',1);click(b,'editPalette');b.d.getElementById('paletteName').value='Мои портреты';b.d.querySelector('#paletteEditor button').click();value(b,'paletteHex','#123456');click(b,'applyPaletteColor');click(b,'savePalette');assert.equal(b.d.getElementById('paletteSelect').selectedOptions[0].textContent,'Мои портреты');assert.equal(JSON.parse(b.w.localStorage.getItem('contour-palettes'))[1].colors[0],'#123456');click(b,'newPalette');click(b,'addPaletteColor');click(b,'savePalette');assert.equal(b.d.getElementById('paletteSelect').options.length,presetCount+1);
 // Download formats and .contour project re-open, invalid TIFF cannot mutate canvas.
 for(const format of ['contour','png','jpeg','tiff']){click(b,'saveProject');value(b,'saveFormat',format);click(b,'doSave');await settle();const item=b.w.testDownloads.at(-1);assert.ok(item.blob);assert.match(item.name,new RegExp(format==='jpeg'?'jpg$':format==='contour'?'contour$':format+'$'));const bytes=Buffer.from(await item.blob.arrayBuffer());if(format==='contour'){const p=JSON.parse(bytes);assert.equal(p.layers.length,n);fs.writeFileSync('/workspace/scratch/overhaul.contour',bytes);}else if(format==='tiff'){const image=F.decodeTiff(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),(w,h)=>assert.ok(w*h<=24000000));assert.equal(image.width,960);fs.writeFileSync('/workspace/scratch/overhaul.tiff',bytes);}else{const img=await native.loadImage(bytes);assert.equal(img.width,960);}}
 b.w.close();
 // Pure lasso masks and independent TIFF exact transparent RGBA roundtrip.
 assert.deepEqual([...C.polygonMask([{x:1,y:1},{x:4,y:1},{x:4,y:4},{x:1,y:4}],5,5)],Array.from({length:25},(_,i)=>Number(i%5>=1&&i%5<4&&Math.floor(i/5)>=1&&Math.floor(i/5)<4)));
 const image={width:2,height:2,data:Uint8ClampedArray.from([0,1,2,0,10,20,30,255,200,100,50,128,255,255,255,255])},encoded=F.encodeTiff(image),decoded=F.decodeTiff(encoded.buffer,()=>{});assert.deepEqual(decoded,image);fs.writeFileSync('/workspace/scratch/rgba-test.tiff',encoded);assert.throws(()=>F.decodeTiff(encoded.slice(0,150).buffer,()=>{}));
 // Automatic draft still restores layers and allows undo after a new drawing.
 let stored;const store={read:async()=>stored||null,write:async p=>stored=p},q=harness(store);await settle();blank(q);shape(q,[[100,100]],'#3f7f8a',3);const expected=q.image();await runTimer(q);assert.ok(stored);const recovered=harness(store);await settle();click(recovered,'restoreDraft');for(let i=0;i<60&&recovered.d.getElementById('restoreDraft').disabled;i++)await new Promise(r=>setTimeout(r,10));assert.deepEqual(recovered.image(),expected);recovered.stroke([[200,200]]);click(recovered,'undo');assert.deepEqual(recovered.image(),expected);q.w.close();recovered.w.close();
 console.log('Overhaul verified: contextual UI, hard brush edges, square brush, Alt/R return, +/- modes, lasso, clipboard, move/scale/cancel, crop dimension undo/redo, background, palettes, all exports, TIFF RGBA, draft recovery.');
})().catch(e=>{console.error(e);process.exitCode=1});
