const assert=require('node:assert/strict'),fs=require('node:fs');
const {harness,runTimer,settle,native}=require('./harness.cjs'),C=require('../core.js');
const click=(h,id)=>h.d.getElementById(id).click();
function value(h,id,v,event='input'){const el=h.d.getElementById(id);el.value=v;el.dispatchEvent(new h.w.Event(event,{bubbles:true}));}
function blank(h,w=420,height=320){click(h,'newDoc');value(h,'newWidth',w);value(h,'newHeight',height);click(h,'createDoc');h.flushFrames();value(h,'zoom100',100,'change');}
function curve(h){h.d.querySelector('[data-path-tool="curve"]').click();}
function ellipse(cx,cy,rx,ry,angle=0,noisy=true){return Array.from({length:121},(_,i)=>{const t=i/120*Math.PI*2,k=noisy?1+.025*Math.sin(t*7)+.015*Math.cos(t*11):1;return{x:cx+k*rx*Math.cos(t)*Math.cos(angle)-k*ry*Math.sin(t)*Math.sin(angle),y:cy+k*rx*Math.cos(t)*Math.sin(angle)+k*ry*Math.sin(t)*Math.cos(angle)};});}
function bounds(h,color){let x0=1e9,y0=1e9,x1=-1,y1=-1;const data=h.image(),w=h.d.getElementById('display').width;for(let i=0;i<data.length;i+=4)if(data[i]===color[0]&&data[i+1]===color[1]&&data[i+2]===color[2]){const x=i/4%w,y=Math.floor(i/4/w);x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}return{x0,y0,x1,y1,w:x1-x0+1,h:y1-y0+1};}
function holdStroke(h,points){h.event('pointerdown',points[0].x,points[0].y);for(const p of points.slice(1))h.event('pointermove',p.x,p.y);h.flushFrames();}
const rgb=[189,97,82],white=[255,255,255,255];
const pixel=(h,x,y)=>[...h.image().subarray((y*h.d.getElementById('display').width+x)*4,(y*h.d.getElementById('display').width+x)*4+4)];
(async()=>{
 // Fitting: rotated/rough ellipses, event-density independence and negative shapes.
 for(const [rx,ry,angle] of [[60,60,0],[95,35,.65],[25,80,-.4]]){const points=ellipse(170,145,rx,ry,angle),fit=C.recognizeEllipse(points);assert.ok(fit);assert.ok(Math.hypot(fit.cx-170,fit.cy-145)<2);assert.ok(Math.abs(fit.rx-Math.max(rx,ry))<3);assert.ok(Math.abs(fit.ry-Math.min(rx,ry))<3);const dense=points.flatMap((p,i)=>Array(i%7+1).fill(p)),other=C.recognizeEllipse(dense);assert.ok(Math.hypot(other.cx-fit.cx,other.cy-fit.cy)<.1);}
 assert.equal(C.recognizeEllipse(ellipse(170,145,60,60).slice(0,70)),null);assert.equal(C.recognizeEllipse(Array.from({length:50},(_,i)=>({x:i*3,y:i*2}))),null);assert.equal(C.recognizeEllipse(ellipse(20,20,3,3)),null);
 const square=[];for(const [a,b] of [[{x:60,y:60},{x:180,y:60}],[{x:180,y:60},{x:180,y:180}],[{x:180,y:180},{x:60,y:180}],[{x:60,y:180},{x:60,y:60}]])for(let i=0;i<30;i++)square.push({x:a.x+(b.x-a.x)*i/29,y:a.y+(b.y-a.y)*i/29});assert.equal(C.recognizeEllipse(square),null);
 // One continuous path: shared joins, handles, additions, node undo/redo/delete, close and finish.
 let h=harness();blank(h);curve(h);value(h,'brushSize',5);h.stroke([[60,160]]);assert.equal(h.d.getElementById('applyPath').disabled,true);assert.ok(h.image().every((v,i)=>i%4===3?v===255:v===255));h.stroke([[170,100]]);const two=h.image();h.stroke([[300,165]]);const three=h.image();assert.ok(!three.equals(two));assert.match(h.d.getElementById('pathHint').textContent,/3/);h.key('keydown','KeyZ',{ctrlKey:true});assert.ok(h.image().equals(two));h.key('keydown','KeyZ',{ctrlKey:true,shiftKey:true});assert.ok(h.image().equals(three));h.key('keydown','Backspace');assert.ok(h.image().equals(two));h.key('keydown','KeyZ',{ctrlKey:true});assert.ok(h.image().equals(three));h.stroke([[170,100],[170,60]]);assert.ok(!h.image().equals(three));h.key('keydown','Enter');const finished=h.image();assert.equal(h.d.getElementById('applyPath').disabled,true);assert.deepEqual(pixel(h,170,60),[...rgb,255]);click(h,'undo');assert.ok(h.image().every(v=>v===255));click(h,'redo');assert.ok(h.image().equals(finished));h.w.close();
 h=harness();blank(h);curve(h);for(const p of [[80,80],[180,50],[250,150],[90,220]])h.stroke([p]);click(h,'closePath');assert.equal(h.d.getElementById('closePath').getAttribute('aria-pressed'),'true');h.key('keydown','KeyZ',{ctrlKey:true});assert.equal(h.d.getElementById('closePath').getAttribute('aria-pressed'),'false');click(h,'closePath');const closed=h.image();h.event('contextmenu',0,0,{button:2});assert.ok(h.image().equals(closed));assert.equal(h.d.getElementById('applyPath').disabled,true);click(h,'undo');assert.ok(h.image().every(v=>v===255));h.w.close();
 // Closely spaced controls do not steal a click exactly on their anchor.
 h=harness();blank(h);curve(h);for(const p of [[60,100],[80,100],[100,100]])h.stroke([p]);h.stroke([[80,100],[80,70]]);h.key('keydown','Enter');assert.deepEqual(pixel(h,80,70),[...rgb,255]);h.w.close();
 // Cancelling while the very first node is still held restores an empty canvas.
 for(const cancel of ['pointercancel','Escape']){h=harness();blank(h);curve(h);h.event('pointerdown',70,160);h.event('pointermove',90,150);if(cancel==='Escape')h.key('keydown','Escape');else h.event('pointercancel',90,150);assert.equal(h.d.getElementById('cancelPath').disabled,true);assert.ok(h.image().every(v=>v===255));h.w.close();}
 // Alt keeps the curve tool and links both handles; near-circles snap without Shift.
 h=harness();blank(h);curve(h);h.stroke([[70,160],[95,160]]);h.stroke([[170,100],[195,100]]);h.stroke([[300,160]]);const smooth=h.image();h.key('keydown','AltLeft',{altKey:true});assert.equal(h.d.getElementById('pathOptions').hidden,false);h.event('pointerdown',195,100,{altKey:true});h.event('pointermove',210,150,{altKey:true});h.event('pointerup',210,150,{altKey:true});h.key('keyup','AltLeft');assert.ok(!h.image().equals(smooth));h.key('keydown','KeyZ',{ctrlKey:true});assert.ok(h.image().equals(smooth));h.key('keydown','Escape');h.w.close();
 h=harness();blank(h);const nearCircle=ellipse(200,150,68,67);holdStroke(h,nearCircle);await runTimer(h);assert.match(h.d.getElementById('quickShapeHint').textContent,/Круг/);const round=bounds(h,rgb);assert.ok(Math.abs(round.w-round.h)<=2);h.event('pointerup',nearCircle.at(-1).x,nearCircle.at(-1).y);h.w.close();
 // Hold-to-fit, live circle conversion, scale/rotation, exact edges and a single undo.
 h=harness();blank(h);value(h,'brushSize',7);const points=ellipse(200,150,90,42,.4);holdStroke(h,points);const rough=h.image();await runTimer(h);assert.equal(h.d.getElementById('quickShapeHint').hidden,false);assert.ok(!h.image().equals(rough));h.key('keydown','ShiftLeft',{shiftKey:true});assert.match(h.d.getElementById('quickShapeHint').textContent,/Круг/);const circle=bounds(h,rgb);assert.ok(Math.abs(circle.w-circle.h)<=1);h.key('keyup','ShiftLeft');assert.match(h.d.getElementById('quickShapeHint').textContent,/Овал/);const start=points.at(-1),next={x:200+(start.x-200)*1.15,y:150+(start.y-150)*1.15};h.event('pointermove',next.x,next.y);h.event('pointerup',next.x,next.y);const fitted=h.image();for(let i=0;i<fitted.length;i+=4)assert.ok(fitted[i]===255&&fitted[i+1]===255&&fitted[i+2]===255||fitted[i]===rgb[0]&&fitted[i+1]===rgb[1]&&fitted[i+2]===rgb[2]);click(h,'undo');assert.ok(h.image().every(v=>v===255));click(h,'redo');assert.ok(h.image().equals(fitted));h.w.close();
 // Opt-out and unclosed paths leave the ordinary brush stroke alone; Escape restores pixels.
 h=harness();blank(h);h.d.getElementById('quickShapeEnabled').checked=false;holdStroke(h,ellipse(200,150,70,45));const before=h.image();await runTimer(h);assert.ok(h.image().equals(before));assert.equal(h.d.getElementById('quickShapeHint').hidden,true);h.key('keydown','Escape');assert.ok(h.image().every(v=>v===255));h.d.getElementById('quickShapeEnabled').checked=true;holdStroke(h,ellipse(200,150,70,45).slice(0,60));await runTimer(h);assert.equal(h.d.getElementById('quickShapeHint').hidden,true);h.key('keydown','Escape');h.w.close();
 // Selection/mask restrictions survive shape replacement, with uniform opacity across redraws.
 h=harness();blank(h);h.d.querySelector('[data-selection-mode="rect"]').click();h.stroke([[160,80],[320,220]]);click(h,'maskFromSelection');click(h,'deselect');h.d.querySelector('[data-tool="brush"]').click();value(h,'brushSize',9);value(h,'brushOpacity',50);holdStroke(h,ellipse(200,150,85,48));await runTimer(h);h.event('pointermove',300,150);h.event('pointermove',285,150);h.event('pointerup',285,150);const data=h.image();let colored=0;for(let y=0;y<320;y++)for(let x=0;x<420;x++){const i=(y*420+x)*4;if(data[i]!==255||data[i+1]!==255||data[i+2]!==255){colored++;assert.ok(x>=160&&x<320&&y>=80&&y<220);assert.ok(data[i]>=220&&data[i]<=223);}}assert.ok(colored>200);h.w.close();
 // Draw the regression fixture through editor tools: a cat, using joined curves and fitted ellipses.
 h=harness();blank(h,640,520);value(h,'color','#25303a');value(h,'brushSize',6);curve(h);for(const p of [[220,210],[205,100],[275,150],[365,150],[435,100],[420,210],[414,260],[320,292],[226,260]])h.stroke([p]);click(h,'closePath');click(h,'applyPath');h.d.querySelector('[data-tool="brush"]').click();for(const shape of [ellipse(320,370,92,105),ellipse(277,208,15,21),ellipse(362,208,15,21)]){holdStroke(h,shape);await runTimer(h);const end=shape.at(-1);h.event('pointerup',end.x,end.y);}h.d.querySelector('[data-path-tool="line"]').click();for(const path of [[[308,243],[320,252]],[[320,252],[332,243]],[[320,252],[320,265]],[[240,246],[170,233]],[[240,255],[166,258]],[[398,246],[472,233]],[[398,255],[474,258]]])h.stroke(path);curve(h);for(const path of [[[410,398],[440,430]],[[485,415],[515,398]],[[515,360],[495,330]],[[478,330],[458,345]]])h.stroke(path);click(h,'applyPath');click(h,'saveProject');click(h,'doSave');await settle();const p=JSON.parse(await h.w.testDownloads.at(-1).blob.text());fs.writeFileSync('/workspace/scratch/kontur-cat-040.contour',JSON.stringify(p));fs.writeFileSync('/workspace/scratch/kontur-cat-040.png',h.back(h.d.getElementById('display')).toBuffer('image/png'));assert.equal(p.layers.length,2);assert.ok(bounds(h,[37,48,58]).w>300);h.w.close();
 console.log('Paths and shapes verified: continuous shared-node curves, smooth controls, node undo/redo/delete/closure/finish, held ellipse fitting and Shift circle, scaling, opt-out, negative shapes, mask/opacity/hard edges, single-step pixel undo and a cat drawn through editor tools.');
})().catch(e=>{console.error(e);process.exitCode=1});
