const assert=require('node:assert/strict'),vm=require('node:vm');
const C=require('../core.js'),{harness,settle,runTimer,native}=require('./harness.cjs');
const click=(h,id)=>h.d.getElementById(id).click();
function set(h,id,v,event='change'){const e=h.d.getElementById(id);e.value=v;e.dispatchEvent(new h.w.Event(event,{bubbles:true}));}
function tool(h,t){const e=h.d.querySelector(`[data-path-tool="${t}"],[data-selection-mode="${t}"],[data-tool="${t}"]`);e.click();}
function blank(h,w=100,height=80){set(h,'newWidth',w);set(h,'newHeight',height);click(h,'createDoc');h.flushFrames();set(h,'zoom100',100);}
const px=(h,x,y)=>[...h.image().subarray((y*h.d.getElementById('display').width+x)*4,(y*h.d.getElementById('display').width+x)*4+4)];
const white=[255,255,255,255],red=[189,97,82,255],blue=[18,52,86,255];
function square(h,size=1){h.d.querySelector('[data-brush-shape="square"]').click();set(h,'brushSize',size,'input');}
async function project(h){click(h,'saveProject');click(h,'doSave');await settle();return JSON.parse(await h.w.testDownloads.at(-1).blob.text());}
async function choose(h,id,file){const input=h.d.getElementById(id);Object.defineProperty(input,'files',{configurable:true,value:[file]});input.dispatchEvent(new h.w.Event('change'));await settle();for(let i=0;i<100;i++){if(id==='imageInput'&&h.d.getElementById('projectPreviewDialog').open||id==='referenceInput'&&!h.d.getElementById('referenceCanvas').hidden)break;await new Promise(r=>setTimeout(r,10));}}
function gapFixture(gap){const w=30,h=30,d=new Uint8ClampedArray(w*h*4).fill(255);const black=(x,y)=>d.set([0,0,0,255],(y*w+x)*4);for(let x=5;x<=24;x++){black(x,5);black(x,24);}for(let y=5;y<=24;y++){black(5,y);black(24,y);}for(let x=13;x<13+gap;x++)d.set([255,255,255,255],(5*w+x)*4);return d;}
(async()=>{
 for(const gap of [1,2,3,4]){const d=gapFixture(gap),seed=15*30+15;assert.equal(C.fillRegion(d,30,30,seed,0,null,0)[0],1);const closed=C.fillRegion(d,30,30,seed,0,null,gap);assert.equal(closed[0],0,'close '+gap+'px');assert.equal(closed[seed],1);assert.equal(closed[5*30+5],0);if(gap>1)assert.equal(C.fillRegion(d,30,30,seed,0,null,gap-1)[0],1,'leave larger gap open');}
 const messages=[],worker={self:{postMessage:m=>messages.push(m)}};vm.createContext(worker);vm.runInContext(C.workerSource,worker);const data=gapFixture(2);worker.self.onmessage({data:{kind:'source',data}});worker.self.onmessage({data:{kind:'fill',id:3,width:30,height:30,seed:465,tolerance:0,gap:2}});assert.deepEqual([...messages[0].result],[...C.fillRegion(data,30,30,465,0,null,2)]);
 let h=harness();blank(h);square(h);h.stroke([[50,0],[50,79]]);const original=h.image();tool(h,'fill');set(h,'color','#123456','input');h.event('pointermove',20,40);await runTimer(h);assert.deepEqual(h.image(),original,'hover never changes pixels');const overlay=h.back(h.d.getElementById('overlay')).getContext('2d').getImageData(20,40,1,1).data;assert.equal(overlay[3],90);h.event('pointerdown',20,40,{shiftKey:true});h.event('pointermove',80,40,{shiftKey:true});h.event('pointerup',80,40,{shiftKey:true});assert.deepEqual(px(h,20,40),blue);assert.deepEqual(px(h,80,40),blue);assert.deepEqual(px(h,50,40),red);const filled=h.image();click(h,'undo');assert.deepEqual(h.image(),original,'one undo for multiple areas');click(h,'redo');assert.deepEqual(h.image(),filled);h.w.close();
 h=harness();blank(h);click(h,'symmetryToggle');square(h,3);h.stroke([[20,30]]);assert.deepEqual(px(h,20,30),red);assert.deepEqual(px(h,79,30),red);const symmetric=h.image();click(h,'undo');assert.deepEqual(px(h,20,30),white);click(h,'redo');assert.deepEqual(h.image(),symmetric);h.event('pointermove',20,30);assert.equal(h.d.getElementById('mirroredToolCursor').hidden,false);h.key('keydown','KeyF');h.stroke([[20,30],[50,30]]);h.key('keyup','KeyF');assert.equal(h.d.getElementById('brushSize').value,'13');assert.deepEqual(h.image(),symmetric,'size drag does not paint');click(h,'symmetryToggle');h.key('keydown','KeyJ');assert.equal(h.d.getElementById('canvasWrap').classList.contains('mirrored'),true);assert.deepEqual(h.image(),symmetric,'mirror is view only');h.key('keydown','KeyJ');tool(h,'rect');h.stroke([[10,10],[30,30]]);const path=h.d.querySelector('#selectionOutline path').getAttribute('d');h.key('keydown','KeyD');h.stroke([[15,15],[35,25]]);h.key('keyup','KeyD');assert.notEqual(h.d.querySelector('#selectionOutline path').getAttribute('d'),path);assert.deepEqual(h.image(),symmetric,'D moves contour only');h.w.close();
 h=harness();blank(h);tool(h,'rectangle');set(h,'shapePaintMode','both');set(h,'shapeFillColor','#123456','input');set(h,'brushSize',4,'input');h.stroke([[10,10],[40,40]]);assert.deepEqual(px(h,25,25),blue);assert.deepEqual(px(h,10,20),red);for(let i=0,d=h.image();i<d.length;i+=4)assert.ok([white,red,blue].some(c=>c.every((v,j)=>d[i+j]===v)),'hard figure edges');const shape=h.image();click(h,'undo');assert.deepEqual(px(h,25,25),white);click(h,'redo');assert.deepEqual(h.image(),shape);for(const t of ['ellipse','triangle','polygon']){tool(h,t);h.stroke([[50,10],[90,50]]);click(h,'undo');assert.deepEqual(h.image(),shape);}h.w.close();
 h=harness();blank(h);square(h,10);h.stroke([[30,30]]);const before=h.image();h.d.querySelector('.layer-row.active .alpha-lock').click();set(h,'color','#123456','input');square(h,40);h.stroke([[30,30]]);assert.deepEqual(px(h,30,30),blue);assert.deepEqual(px(h,15,15),white);const locked=h.image();let p=await project(h);assert.equal(p.layers[1].alphaLocked,true);assert.ok(p.preview.startsWith('data:image/png;'));const recovered=harness();await choose(recovered,'imageInput',{name:'cat.contour',text:async()=>JSON.stringify(p)});assert.equal(recovered.d.getElementById('projectPreviewDialog').open,true);assert.equal(recovered.d.getElementById('welcome').hidden,false,'preview does not replace document');click(recovered,'confirmProjectPreview');assert.deepEqual(recovered.image(),locked);assert.equal(recovered.d.querySelector('.alpha-lock').getAttribute('aria-pressed'),'true');recovered.w.close();click(h,'undo');assert.deepEqual(h.image(),before);click(h,'redo');assert.deepEqual(h.image(),locked);click(h,'addLayer');tool(h,'brush');square(h,4);h.stroke([[60,30]]);const layered=h.image();click(h,'mergeDown');assert.equal(h.d.querySelectorAll('.layer-row').length,2);assert.deepEqual(h.image(),layered);click(h,'undo');assert.equal(h.d.querySelectorAll('.layer-row').length,3);assert.deepEqual(h.image(),layered);click(h,'mergeVisible');assert.equal(h.d.querySelectorAll('.layer-row').length,1);assert.deepEqual(h.image(),layered);click(h,'undo');assert.deepEqual(h.image(),layered);h.w.close();
 h=harness();blank(h);set(h,'color','#13579b','input');assert.equal(h.d.querySelectorAll('#recentColors button').length,1);set(h,'color','#13579b','input');assert.equal(h.d.querySelectorAll('#recentColors button').length,1);h.d.querySelector('#palette button').click();assert.equal(h.d.querySelectorAll('#recentColors button').length,1,'preset does not enter recent colors');click(h,'newPalette');set(h,'gradientStart','#000000','input');set(h,'gradientEnd','#ffffff','input');click(h,'generateGradient');click(h,'savePalette');const palette=JSON.parse(h.w.localStorage.getItem('contour-palettes')).at(-1);assert.equal(palette.colors.length,20);assert.equal(palette.colors[0],'#000000');assert.equal(palette.colors.at(-1),'#ffffff');assert.equal(new Set(palette.colors).size,20);set(h,'canvasPreset','a4');assert.equal(h.d.getElementById('newWidth').value,'2480');assert.equal(h.d.getElementById('newHeight').value,'3508');h.w.prompt=()=> 'Мой холст';click(h,'saveCanvasPreset');h.w.prompt=()=> 'Переименован';click(h,'renameCanvasPreset');assert.equal(JSON.parse(h.w.localStorage.getItem('contour-canvas-presets'))[0].name,'Переименован');
 const c=native.createCanvas(20,10);c.getContext('2d').fillStyle='#123456';c.getContext('2d').fillRect(0,0,20,10);const f=new Blob([c.toBuffer('image/png')],{type:'image/png'});f.name='reference.png';await choose(h,'referenceInput',f);const rc=h.d.getElementById('referenceCanvas');rc.getBoundingClientRect=()=>({left:0,top:0,width:20,height:10});h.d.getElementById('referenceToPalette').checked=true;rc.dispatchEvent(new h.w.MouseEvent('pointerdown',{bubbles:true,clientX:4,clientY:4}));assert.equal(h.d.getElementById('color').value,'#123456');assert.ok(JSON.parse(h.w.localStorage.getItem('contour-palettes')).at(-1).colors.includes('#123456'));click(h,'minimizeReference');assert.equal(h.d.getElementById('referenceWindow').classList.contains('minimized'),true);click(h,'minimizeReference');assert.equal(h.d.getElementById('referenceWindow').classList.contains('minimized'),false);h.w.close();
 console.log('0.6.0 workflows verified: exact gap thresholds, worker equivalence, non-mutating hover, Shift multi-fill undo, symmetry/cursors, F size, D contour move, view mirror, hard-edge filled figures, alpha lock/project preview, merge undo, recent colors, 20-slot gradient, named presets and reference eyedropper.');
})().catch(e=>{console.error(e);process.exitCode=1});
